### ISSUE TITLE
Nier Automata [*.wem] files aren't looping at all

### ISSUE THREAD

**Issue by Skeith86** [losnoco/vgmstream#139]
Hello, I have the foobar 2000 plugin, and have been trying to run the files through it, but it won't loop. How may I solve this?

**Comment by kode54** [comment]
Paging @bnnm to this topic. But I don't think those files have viable loop points.

**Comment by bnnm** [comment]
The file doesn't have "normal" loops points like other .wem, but it does have what looks like a loop start (last "cue" def).
I haven't figured out if there is a loop end somewhere in the file or if the game manually loops it, I'll try. Other Platinum games are like this too.

**Comment by Skeith86** [comment]
Thanks :)

**Comment by bnnm** [comment]
I checked some more and the definitely the file has the loop start sample "label", but not the loop end, none of the extra fields in the .wem mean anything of that sort.
I'm guessing Platinum is using some custom event for looping to jump to this label at some point (see this [MGR Wwise commentary](https://www.audiokinetic.com/about/news/235-metal-gear-rising-revengeance/)).

Next I tested if some companion file holds loop ends (PT .wems always come with a "SoundMacro.bxm", "WwiseInfo.wai" and such). I didn't immediatedly see any loop-like value or any .wem identifier. At best the loop info is in one of those files but must be figured out, and at worst they are in some data file somewhere else. 

I'm afraid there is nothing else I can do :(

**Comment by Skeith86** [comment]
oh well, thank you for trying :)

**Comment by CosmicDreamsOfCode** [comment]
Mario Rabbids does the same sot of stuff with it's WEM files it seems.

**Comment by CosmicDreamsOfCode** [comment]
Was any progress ever made on this?

**Comment by NicknineTheEagle** [comment]
To my knowledge, Wwise WEM files themselves never have loop points, any and all info about loops, transitions, sequences, etc is stored inside BNK files and BNK format has never been fully documented.

**Comment by CosmicDreamsOfCode** [comment]
Starlink Battle For Atlas has loop data in its WEM files.
I've been looking for months with Mario + Rabbids and I did have a feeling the data was in the BNK files. Specifically the HIRC section as that stores all the Wwise event information

**Comment by bnnm** [comment]
Wwise loops can be handled now with this: https://github.com/bnnm/wwiser
