### ISSUE TITLE
test.exe not finding loop points in this fsb file.

### ISSUE THREAD

**Issue by MichaelPriebe** [losnoco/vgmstream#151]
[music.zip](https://github.com/kode54/vgmstream/files/1525324/music.zip)
The loop points of the first substream of this fsb is at `0` and `2059263`, using `-l 10` generates a file that just plays once, meaning it did not find these loop points and just played through once.

FSBExtractor finds these loop points, here they are for the rest of the substreams too:
![image](https://user-images.githubusercontent.com/5238952/33531877-83d92082-d861-11e7-9339-7a7b1fc54ede.png)

**Comment by kode54** [comment]
Paging @bnnm, in case he's faster at examining these files.

**Comment by bnnm** [comment]
vgmstream does find the loop points, but then disables them as it assumes it's an unwanted full loop (ie. reaches the end then repeats, the file doesn't actually loop gracefully).

I'm not sure if we really want to enable looping here but meanwhile you can use the -e flag in test.exe (full loop).

**Comment by MichaelPriebe** [comment]
But if you look, the loop end is not the same place as the last sample. 2059**776**  vs 2059**263**

**Comment by bnnm** [comment]
That's normal for FSB5, other files do full loops like that. The end point falls in a silent part.

Maybe you could point files or subsongs that would benefit from maintaining such full loops? (ie. they don't fade). I know of a bunch that do in FSB4, so it's not disabled there, but not in FSB5.
