### ISSUE TITLE
G1l playback is messed up when built on Mac OS X

### ISSUE THREAD

**Issue by tellowkrinkle** [losnoco/vgmstream#17]
I built the test program (r1040) on my computer running 10.10.3 Yosemite, and everything works great except g1l files, which are all messed up.  [Here's a sample I made with the version I built](https://drive.google.com/open?id=0Bwl14FRHtUfqSExwYmdyc24yNjQ&authuser=0) vs [one I made by running the windows version with wine](https://drive.google.com/open?id=0Bwl14FRHtUfqaUxSSEFQeXZXM28&authuser=0).

**Comment by kode54** [comment]
Test this again?

**Comment by tellowkrinkle** [comment]
Yep works fine now
