### ISSUE TITLE
PS1 - *.VAB framework stuff

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#200]
so, i'm here just to request some support for this soundbank file that has been "common" among most PS1 games... without further ado, here it is.

[ps1.zip](https://github.com/kode54/vgmstream/files/1767718/ps1.zip)

**Comment by NicknineTheEagle** [comment]
You can get the the audio files layout from the header but the problem is that there's no way to get the sample rate and it can be different even with a single VAB bank.

**Comment by AnonBaiter** [comment]
heh

if nothing else though, i guess i can close this issue

**Comment by NicknineTheEagle** [comment]
Here's my BMS script for VAB files:
```
goto 0x12
get PROGRAMS short
get TONES short
get WAVES short

# Skip header and program data
goto 0x820
# Skip tone data
set TONES_SIZE long 0x200
math TONES_SIZE * PROGRAMS
goto TONES_SIZE 0 SEEK_CUR
savepos WAVE_OFF
math WAVE_OFF + 0x200
get ZERO short

for i = 0 < WAVES
	get SIZE short
	math SIZE * 8
	get FILENAME BASENAME
	string NAME p= "%s_%d.vgmstream" FILENAME i
	log NAME WAVE_OFF SIZE
	math WAVE_OFF + SIZE
next i
```
The size stored seems to differ between games, though, e.g. it needs to be divided by 2 for Crash Bandicoot, it's weird.

**Comment by AnonBaiter** [comment]
noice
i can flesh out this entire script for you if i wanted to

**Comment by NicknineTheEagle** [comment]
@bnnm Could you look more into this format? I couldn't find sample rates in the header but it seems unlikely for them to not be specified anywhere since they can be different within a single bank file. Maybe they're stored in some weird way like a "mode" index.

**Comment by bnnm** [comment]
No sample rate AFAIK. Here is the official spec: https://www.sendspace.com/file/d7cw12

**Comment by NicknineTheEagle** [comment]
Ohhhh, this is useful, thanks.
