### ISSUE TITLE
[PSP] Patapon .vag and .sgd doesn't decode correctly

### ISSUE THREAD

**Issue by OwocekTV** [losnoco/vgmstream#291]
Hello,
I'm trying to decode .vag sounds from Patapon on PSP. They are headerless and stored in SGXD by default, but I managed to individually extract them and apply the header with correct size and sample rate. 

SGXD in vgmstream extracts only one sound file, while there are multiple others inside.

After decoding an individual file from SGXD with correct sample rate and data, the output file is sped up (about 4x faster). Same thing happens when I decode SGXD, it outputs only one file and it is 4x sped up as well.

Individual sample .vag (with added header):
https://www.dropbox.com/s/2y5achbrz3yx868/ptp_btl_bgm001_voice_header.vag?dl=1
(headerless):
https://www.dropbox.com/s/1p96iggxdgmhnxz/ptp_btl_bgm001_voice.vag?dl=1

Sample SGXD:
https://www.dropbox.com/s/kb1h4n34t43tqna/ptp_btl_bgm_voice.sgd?dl=1

Expected output:
https://www.dropbox.com/s/wxgk0qjc9t7biu0/expected_result.wav?dl=1

(in SGXD expected output is 24 sound files)
Everything here is 4-bit Sony ADPCM.

Thank you :)

**Comment by bnnm** [comment]
The SGXD header does say sample rate is 44100, but in reality it should be 11025. If you force that sample rate in the resulting .wav file (for example in Audacity: track > "Set Rate" = 11025, or hex-editting) your files will play correctly.

I tried but didn't find any way to detect this oddity, so I assume the game must be forcing the sample rate externally from the SGXD to 11025. I've only seen SGXD using 44100 or 48000, and all play correctly, so maybe it's a limitation of Sony's SGXD library and Patapon devs forced 11025 to skip that limitation.

Anyway, I don't think this can be fixed, unfortunately.

Note that vgmstream can play those 24 subsongs (provided you use a recent-ish version). If you are using test.exe, you need to pass the subsong number with "-s N", starting from 1, while in foobar/winamp it's done automatically).

**Comment by OwocekTV** [comment]
Yes, the sample rate in the SGXD is in fact 44100, and this is what makes it interesting, because the game also plays these sound files at 44100. I managed to find the SGXD file in the memory of the game, so I could change the bitrate manually, to see the change.

And it does change! It slows down a lot when I set the bitrate to 11025. About the file being sped up, I had the same issue in MFAudio, and the reason behind it was most likely 16 bit sample size. Sony ADPCM is 4 bit sample size, so it makes sense that the bitrate of 11025 is correct, because 11025 is 44100 4x smaller, so is 4 bit 4x smaller than 16 bit. Sadnly I can't change the sample size to 4 bit in MFAudio, so I cannot verify it, but this is my theory.

Next thing that makes me think that it is not 11025 is the audio quality. When the sound is being converted into 11025 Hz (or slowed down 4 times), the quality drops drastically, and it is nowhere near the quality that I can achieve in the game.

Here is a little demo I recorded just now, to show you that the sound file in fact plays at 44100 by default, and that SGXD supports lower bitrates up to 0.

https://www.youtube.com/watch?v=BYm4bTV1lpY

I'm looking forward to resolving this issue, as I said my current guess is that the sound file is not being read with 4 bit sample size, but of course I can be very wrong about that.

(Also, why the .vag with added header has a long silence after conversion? I don't see it to be silent in the .vag sound data)

**Comment by bnnm** [comment]
If I understood you correctly, I think that confirms what I said.
- When SGXD header is 44100, game forces it to plays the file at 44100/4 = 11025 (x4 slower)
- If you change the SGXD header manually (I think?) to 11025, game plays the file at 11025/4 = 2756 (x16 slower).

About your file sounding better in game, that's normal. After ADPCM is converted to PCM/wav, the game filters it to sound better, and I believe it's also upsampled from 11025 to 44100 (PSP's hardware sample rate). Because those filters aren't well understood vgmstream can't simulate them.

Bit size and sample rate / play speed aren't related, since decoding PS-ADPCM isn't affect by that. 


Also, your fake .vag has extra silence because the header wasn't correctly formed. Data size (value at 0x0c) is much bigger than actual data.

**Comment by bnnm** [comment]
Sample rate can be forced via .txtp now: https://github.com/losnoco/vgmstream/blob/master/doc/TXTP.md#force-sample-rate

I assume those Patapon sfx are being played as "cues" (wave with config) possibly with pitch applied. vgmstream can only play the waves so there is little we can so other than forcing sample rate externally.
