### ISSUE TITLE
Update EA audio codecs to include/play/read .dat files of Harry Potter Quidditch World Cup (PC and/or other consoles)

### ISSUE THREAD

**Issue by Puterboy1** [losnoco/vgmstream#297]
I strongly suggest it, even though you can rename the banks.dat to .bnk and dat.dat to .str or .mus, but then, the dialogue cuts off after 22 seconds or so. I think viewing these files from the PC version should serve you best.

SFX: https://drive.google.com/open?id=1zbGHXIyWhJAvJgTWHaijK7Gk35gcGGD0
Dialogue: https://drive.google.com/open?id=12YIhvA4ySXgJB06R5ObUxT2NWfRc1Jpy

**Comment by bnnm** [comment]
You must split those files, by "BNKl" and "SCHl". There is nothing vgmstream can do.

**Comment by Puterboy1** [comment]
How do you split them?
