### ISSUE TITLE
Automatic HCA Subkey not working for certain HCAs

### ISSUE THREAD

**Issue by slashiee** [losnoco/vgmstream#332]
I've noticed that when adding the 1.3.0 subkeys for the Dragalia Lost HCAs, some of them would fail to decrypt. There are times where one HCA in an ACB will work while the rest don't.

The following zip contains an ACB (with the necessary AWB) where an issue like that occurs. Without an .hcakey with the proper data, only the first HCA in the ACB (which should be the instrumental) will work. Making a .hcakey with the proper data allows for all the HCAs to decrypt.

[BGM_IN_BATTLE_0002_01.zip](https://github.com/kode54/vgmstream/files/2688998/BGM_IN_BATTLE_0002_01.zip)

The next zip contains an ACB where only one HCA fails to decrypt, being the second one. Once again, creating a .hcakey fixes the issue.

[BGM_IN_RAID_0001_01.zip](https://github.com/kode54/vgmstream/files/2688999/BGM_IN_RAID_0001_01.zip)

**Comment by bnnm** [comment]
Those songs start with a long silence, causing the key detector to give up early. I'll tweak it, but if you can compile go [here](https://github.com/kode54/vgmstream/blob/master/src/coding/hca_decoder.c#L154), set `#define HCA_KEY_MAX_BLANK_FRAMES 400` and please test if all songs are working with that value or maybe 500 (it's not a big deal to go high but I'd like to keep it sane).

**Comment by kode54** [comment]
There may be an issue where the matching algorithm will outright fail if it has fewer than a certain number of frames.

**Comment by bnnm** [comment]
Some sfx are too small to get accurate keys, it doesn't fail per se but wrong keys can give seemingly listenable results, I'll have to improve detection.

There is also a copy pasta bug that shows if you change HCA_KEY_MAX_TEST_FRAMES: [this line](https://github.com/kode54/vgmstream/blob/master/src/coding/hca_decoder.c#L207) should be
 `if (total_score > 0 && total_score <= HCA_KEY_MAX_ACCEPTABLE_SCORE) {`

**Comment by slashiee** [comment]
PR #335 seems to fix all the issues that I've mentioned. However, I've just discovered that [BGM_IN_STORY_0009_04](https://github.com/kode54/vgmstream/files/2705581/BGM_IN_STORY_0009_04.zip) has two HCAs that don't decrypt until you ignore 900 frames. Could increasing this cause any issues in the future?

**Comment by bnnm** [comment]
Should't cause issues, updated but feel free to commit increases in the future.

It could simply skip all frames until a non-blank file, but huge numbers of skips would be unusual so I'd rather set it as needed to keep an eye on it.

**Comment by slashiee** [comment]
Since Skyth and I found more of the audio files, this should *hopefully* be the last change to the value: [BGM_OUT_0006_04](https://github.com/kode54/vgmstream/files/2705918/BGM_OUT_0006_04.zip) requires it to be set to 1200 for the vocal track to decrypt.

**Comment by bnnm** [comment]
Updated.

**Comment by bnnm** [comment]
From the few I tried they are just missing subkeys (16b LE value at 0x0e in the AWB). Ex:
- VO_CHR_110310_01_CASTLE > 0x7c6b
- VO_CHR_110311_01_EVENTIN_20404 > 0x7b93
