### ISSUE TITLE
CRI ADX 4-bit ADPCM won't play after updated component.

### ISSUE THREAD

**Issue by gutsman1986** [losnoco/vgmstream#356]
Only standard ADX files play properly, however CRI ADX with a 24000Hz sample rate refuse to play.
[00003_e100002_003_0004.zip](https://github.com/losnoco/vgmstream/files/2778804/00003_e100002_003_0004.zip)

**Comment by kode54** [comment]
I should remove the obsolete decoders from my old plugin, some of the others are still useful, or useful for other reasons, like raw CD reading for XA files.
