### ISSUE TITLE
How to use VGMstream to extract from FSB files?

### ISSUE THREAD

**Issue by Xehanort88** [losnoco/vgmstream#362]
So, for listening to FSB files (smaller than a certain amount of either entries or MB) VGM works great, I was wondering whether it could also be used for extracting said audio from the FSB, or if someone here can recommend a way to get the audio off with as little quality loss as possible.

**Comment by bnnm** [comment]
You can make .txtp files to play single subsongs: https://github.com/losnoco/vgmstream/blob/master/doc/TXTP.md#minifiles-for-bank-formats-without-splitters

You may be able to split the fsb into all subfiles using [fsbii](http://hcs64.com/files/fsbii08.zip) (for FSB1~4), or [fsb5_split](http://kirby.cyberbotx.com/fsb5_split.exe) (for FSB5). Both are buggy at times so if resulting files don't play in vgmstream there is nothing we can do.

**Comment by Xehanort88** [comment]
I already am using these to split, I'm talking strictly about format
conversion-extraction from the FSB, to convert to MP3 or FLAC for playback
purposes, it possible at all!
Is that something that can happen via VGMstream?

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il giorno Mar 19 Feb 2019, 22:19 bnnm <notifications@github.com> ha scritto:

**Comment by bnnm** [comment]
vgmstream can only decode to wav, and it's impossible to change it any other way, sorry.

**Comment by Xehanort88** [comment]
Great, good ton know what my options are, thank you!

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Gio 21 Feb 2019, 00:12 bnnm <notifications@github.com> ha scritto:
