### ISSUE TITLE
how to convert wav to hca(2.0) or awb

### ISSUE THREAD

**Issue by Token713** [losnoco/vgmstream#378]
Use latest exe i can convert hca(2.0 format)  to wav,now i want change BGM,i want convert wav to hca,What shall I do?

**Comment by Token713** [comment]
@slashiee
This is my test data,can you tell me how to convert wav to hca,ensure that the transformed hca is 2.0 format.

**Comment by Token713** [comment]
https://www.lanzous.com/i3kce3c
this is testdata.

**Comment by Token713** [comment]
C:\Users\token\Desktop\vvv\bgm\测试数据>VGAudioCli.exe -i: C:\Users\token\Deskto
p\vvv\bgm\测试数据\BGM_CHN_00000000.hca.wav C:\Users\token\Desktop\vvv\bgm\测试
数据\222.hca
索引超出了数组界限。

**Comment by bxaimc** [comment]
Closing this because duplicate thread has been made for same non-issue.

**Comment by EbiDesa** [comment]
hey boy
I dont know how to convert wav to hca with vgaudio.
how its work? I want convert so many wav files.
