### ISSUE TITLE
how to convert wav to hca or awb

### ISSUE THREAD

**Issue by Token713** [losnoco/vgmstream#379]
i use latest vgmstream-latest-test-u.zip,it could convert hca(2.0 format) to wav,now i have new wav song how to convert to hca(2.0) or awbformat?
please help me!

**Comment by CyberBotX** [comment]
vgmstream does decoding only, not encoding.

**Comment by Token713** [comment]
Can decode, why not add decode together？？please help me

**Comment by NicknineTheEagle** [comment]
Because it's not the tool's purpose. vgmstream is a decoder, not an encoder. We cannot assist you with this.

**Comment by bxaimc** [comment]
For creating HCAs, try https://github.com/Thealexbarney/VGAudio

As Nicknine stated, vgmstream’s purpose was to be a decoding library and not an encoder and has been the same over 10 years :P

**Comment by Token713** [comment]
I'm sorry for my rudeness，thanks bro.
Last question：if a hca  encrypted with a custon key，use  vgmstream can decod,does it show that encode is feasible?

**Comment by simontime** [comment]
HCA files use symmetrical crypto, so yes, encrypting _is_ feasible, it's just that the goal of vgmstream is for decoding and playback of files, _not_ encoding.
