### ISSUE TITLE
Recent builds cause txtp channel isolation to behave unexpectedly

### ISSUE THREAD

**Issue by ultrasound1372** [losnoco/vgmstream#380]
I use the foobar2000 plugin. I've noticed while looking through some soundtracks of "New Super Mario Bros. Wii" that the 0 byte trick txtp files I created are now playing odd separations. Instead of playing the first two channels as before, to get rid of the annoying drum loop addition, they now seem to play one part of the first pair on the left and a part of the first pair on the right. Trying to use #c3,4 produces straight silence. The menu bgm also seems to be separated into layers, which the txtp's can no longer isolate. Example files below. Would love to see this fixed ASAP! It should be noted I have downmix set to 2 to avoid foobar panning channels in odd distributions.
[vgmstream_bad_txtp.zip](https://github.com/losnoco/vgmstream/files/3021054/vgmstream_bad_txtp.zip)

**Comment by bnnm** [comment]
I've fixed this. It may take a couple of days before it's added though.

Also if (when the fix is added) you use "C" instead of "c" it'll fully remove other channels and create real stereo files, so you won't need to set downmix in the options.

**Comment by ultrasound1372** [comment]
Thanks for the quick fix. Also nice, we did finally get the complete isolation instead of just muting.
