### ISSUE TITLE
Certain tracks in Tales of the Rays Are silent

### ISSUE THREAD

**Issue by Ristellise** [losnoco/vgmstream#390]
Some tracks in Tales of the Rays either have a 1 sided buzzing noise, or "clicks" for a short second before falling silent.

Samples: <https://mega.nz/#F!SGwzyCgb!KC0sfwd3DPzTA5xcR6qt4g>

The corrected Audio has the samples extracted with VGAudioCli Which can be found [here](https://github.com/Thealexbarney/VGAudio).

vgmstream parameters in foobar:
```
Loop Count: 2
Fade length 10 seconds
Loop normally is selected
Downmix: 16
Disable subsongs and tagfile is unchecked, as with Override title.
```

**Comment by bnnm** [comment]
You need to post the original files as otherwise we can't check.

I tried one rip and all files sound fine (.hca) including what I think are your wavs (gefion_in_game_LOOP.hca and RES_Rays_001.hca). Just to make sure, do you have the latest vgmstream?

**Comment by Ristellise** [comment]
@bnnm the original .hca files are now in the mega.nz folder. I forgot to post it just now.

**Comment by bnnm** [comment]
I've just fixed those.

**Comment by Ristellise** [comment]
Closing Issue since its fixed. Commit: https://github.com/losnoco/vgmstream/commit/e4465fc117463624e00be8eff00be4076414e5ae
