### ISSUE TITLE
Gran Turismo Sport (PS4) - SXD3

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#391]
here's the file.
[[SXD3]M044_2.7z](https://www.sendspace.com/file/1lc7d1)
i got this from some discord server i used to stay on upon request(i was on some discord server about GTSPORT modding among other channels for other games, etcetera that someone invited me to, after quite a wuile i decided i was sick of keeping on with my horrendous AnonBaiter account on my discord so i just quit all discord servers i was on altogether alongside said account and thus i decided to log on to discord with my backup account which is solid_speed), yeah i kept this thing for months now.

don't worry, it's just a merged .sxd1+.sxd2 file but i want to see this supported on vgmstream still.
do keep in mind though that this is the only sxd3 file i have so far and nothing else.

**Comment by bnnm** [comment]
Some other PS4 games use this format (Fate/something and other one IIRC) so there is some merit in adding this, but I need to think about how to handle first.

**Comment by AnonBaiter** [comment]
good point.

**Comment by AnonBaiter** [comment]
right.
just let me know if you managed to get something out of this.

**Comment by bnnm** [comment]
Added this.

**Comment by AnonBaiter** [comment]
my sincere thanks for this.
issue closed.
