### ISSUE TITLE
Encode Ubisoft Format Support

### ISSUE THREAD

**Issue by tulipjustdance** [losnoco/vgmstream#394]
Game such as Just Dance Wii U

**Comment by tulipjustdance** [comment]
Try modification game but need support

**Comment by bxaimc** [comment]
vgmstream is not an encoder

**Comment by tulipjustdance** [comment]
But if can decode can emcode too. add support now

**Comment by bxaimc** [comment]
That’s not how it works. And no.

**Comment by tulipjustdance** [comment]
Why ignore format request? go to fuck!

**Comment by tulipjustdance** [comment]
Why cannot fulfil request?

**Comment by simontime** [comment]
> Why cannot fulfil request?

 Because vgmstream is a decoder, not an encoder, and you're acting like an entitled brat.

**Comment by tulipjustdance** [comment]
> 
> 
> > Why cannot fulfil request?
> 
> Because vgmstream is a decoder, not an encoder, and you're acting like an entitled brat.

Can fuck yourself go away you fagget

**Comment by tulipjustdance** [comment]
Where is encoder? I ask

**Comment by tulipjustdance** [comment]
Hello are there @bxaimc @simontime @kode54
