### ISSUE TITLE
Are PS4 apparent .scd compilation supported?

### ISSUE THREAD

**Issue by Xehanort88** [losnoco/vgmstream#396]
I'd like to know if support for attached formats is already present in vgm stream because, from what my limited Hex Editing allows, these appear to be PS4 scd files grouped together. If not, could you please consider supporting them?

I got these by extracting them from the PS4 1.5+2.5 PKG with LMAT and Noesis. I can't tell if the extraction process was borked up or not, I apologise.
[multi-SCD.zip, but improved file below](https://github.com/losnoco/vgmstream/files/3076179/multi-SCD.zip)

**Comment by Xehanort88** [comment]
UPDATE: I did a bit of research myself, and not all of these files are SCD containers in the sense of being similar to a FSB file with multiple tracks. Some of them are actually even things like 3D models (example attached, see the .mdls file, just in case they're a _sui generis_ scd). So I guess for those a SCD extractor, if such a thing exists, would work, rather than adding to VGM stream compatibility.

I provide here an updated ZIP, more organised about what comes from where.

[recom+1.5.zip](https://github.com/losnoco/vgmstream/files/3077433/recom%2B1.5.zip)

**Comment by bnnm** [comment]
None of those are scd (ignore the text inside), it's just a generic container for other files, not necessarily music, that look like original PS2 assets (.wd sequences, .vag streams, .vsv streams, etc), so there is nothing vgmstream can do.

**Comment by Xehanort88** [comment]
Thanks. Do you know of any QuickBMS script that would help in scanning and eventually extracting any SCD inside?

**Comment by bnnm** [comment]
There are no .scd inside. Just PS2 assets. Better ask the guys at xentax for any extractors.

**Comment by Xehanort88** [comment]
Thanks. Unfortunately the PS2 tools I own don't work.
