### ISSUE TITLE
Abnormal PS4 SCDs or Incorrect Extraction?

### ISSUE THREAD

**Issue by Xehanort88** [losnoco/vgmstream#397]
Hello everyone, thanks a lot for your work on VGM stream.

I'm having some issues getting these files to work in VGM stream, despite the fact that, in theory, they are supposed to be supported SCDs. I did some Hex exploring and their header is SEDBSSCF, but my knowledge stopped at SSCF for the PSP.
[Bug SEDBSSCF.zip](https://github.com/losnoco/vgmstream/files/3076180/Bug.SEDBSSCF.zip)

I got these by extracting them from the PS4 1.5+2.5 PKG with LMAT and Noesis. I can't tell if the extraction process was borked up or not, I apologise. Are the files incorrectly extracted by Noesis or the issue is something else?

Thanks!

**Comment by Xehanort88** [comment]
Ok, in one of my rare moments of genius, I decided to check whether there was more in HxD, and I tried deleting a bit of data before the actual "SEDBSSCF" header. 

The files work.

But I'm concerned whether they may have been extracted incorrectly.

**Comment by bnnm** [comment]
The first 0x10 bytes should be removed, they are added by the pkg (not an extraction error) and not part of the scd

**Comment by Xehanort88** [comment]
Yes, I did that, thanks, I'm glad that I actually got right all by myself once!
Could you please have a look at my other issue, however? That one is really making me bang my head against the wall.
