### ISSUE TITLE
Odd Bitrates reported in some EngineBlack .WAVE Files

### ISSUE THREAD

**Issue by Mohamed00** [losnoco/vgmstream#398]
It seems that when playing some segmented EngineBlack .wave files, example: m_scuttletown_normal.wave from Shantae and the Pirate's Curse (PC) https://drive.google.com/uc?export=download&id=1643GiubPzPa3CYP1eRUC7k6WYpvZJNpb, vgmstream seems to report some rather impossible bitrates, such as 8312 or 24712 kbps.

**Comment by bnnm** [comment]
Should be fixed in the last PR

**Comment by Mohamed00** [comment]
It has. Closing.

**Comment by Mohamed00** [comment]
Hi, it seems that this issue was reintroduced at some point. The file mentioned in this issue is reporting 24712 kbps again.

**Comment by bnnm** [comment]
Fixed.
