### ISSUE TITLE
Problem with some AT9 Files When Played in foobar2000

### ISSUE THREAD

**Issue by Mohamed00** [losnoco/vgmstream#405]
It seems that some AT9 files, when played in foobar2000, pan all the way to the left, even though they claim to be mono. Example file. https://drive.google.com/uc?export=download&id=1RX9RkIS6bfjJ_w761W13n5LNgyu1Fihn. test.exe decodes this file in mono, as far as I can tell it appears to be an issue specific to the foobar2000 component.

**Comment by bnnm** [comment]
I've pushed a fix, though the files themselves are kind of buggy.

**Comment by kode54** [comment]
It's an issue specific to anything which obeys the speaker layout flags. These files, as decoded by FFmpeg, return the speaker layout of "front left". Mono files should have this set to "front center".

**Comment by NicknineTheEagle** [comment]
That's not FFmpeg bug, though, RIFF header is parsed by vgmstream itself and it seems some AT3/AT9 set channel layout flags incorrectly.
