### ISSUE TITLE
BNSF IS14 format "failed opening"

### ISSUE THREAD

**Issue by EmirioBomb** [losnoco/vgmstream#407]
Thanks for your hard works

I'm confused whether vgm supports BNSF IS14 format?
I checked the bnsf.c file, 
/* Late IS14 voice/ambient files use subcodec 0x02 [Tales of Zestiria (PS3/PC), The Idolm@ster 2 (PS3)].

It works well with bnsf(IS22), with G.719.
But if I tried to test.exe *.bnsf(IS14), it said "failed opening"
Here is the BNSF(IS14)
[0000a00b.zip](https://github.com/losnoco/vgmstream/files/3137018/0000a00b.zip)

ISI4 is not supported???
Any help will be great appreciated!!!!!

**Comment by bnnm** [comment]
There are two versions of BNSF IS14. One (with "subcodec" value 0x00) works, and is used in older games. Other (with value 0x02) isn't supported, and your file uses that (probably voice/sfx).
We don't know how to decode them, so they can't be added ATM.

**Comment by EmirioBomb** [comment]
Thanks for expalining the matter, it makes sense to me !!!!
I hope someday, it will be decoded...i must try hard to learn something about it....
Wish you guys  all the best for coming days! Thank you
