### ISSUE TITLE
Front Mission 4 (PS2) - unplayable *.vs files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#408]
filename is self-explanatory
[[front_mission_4_ps2]unplayable_vs_files.7z](https://www.sendspace.com/file/k5nkrr)

sorry i didn't explain this in detail, it's just that i was faced up with these files that couldn't play at all despite the fact that this .vs file format is supported on vgmstream.
what i'm saying is that this said file format is mostly playable with these exceptions you're seeing now as a packed .7z file package.

**Comment by bnnm** [comment]
Fixed

**Comment by AnonBaiter** [comment]
alrighty then
