### ISSUE TITLE
Stuntman (PS2) - *.XAV files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#411]
[[stuntman_ps2_sled50489_demo]XAV_original.7z](https://drive.google.com/open?id=1zsxucMRgwaSXWcy0oM750j9zz8jSpPKq)
yeah...

**Comment by bnnm** [comment]
Some files contain video data, when there is a value at 0x04 (16b height and width). Values at 0x08 and 0x10 seem related to video too. 

Data starts at 0x18 and it's chunked/blocked, there is a small header per block with type(?) byte  + 16b payload size (header size seems 0x08 for video and 0x04 for data chunks). Audio may be PCM16. That's all so far but you could make a vid/audio splitter meanwhile.

**Comment by AnonBaiter** [comment]
well, i just did...
[stuntman_xav.bms](https://github.com/AnonBaiter/le_quickbms_script_compendium/blob/master/stuntman_xav.bms)

**Comment by bnnm** [comment]
Added, also demuxer: https://pastebin.com/s4wZnBCZ

**Comment by AnonBaiter** [comment]
'kay, i'll be taking this for now. thanks.
