### ISSUE TITLE
HCA TXTP Doesn't Loop when Loops are Installed

### ISSUE THREAD

**Issue by mistersiraj11** [losnoco/vgmstream#413]
Hi. When I install loops for my HCA files via TXTP, the songs loop from the beginning instead of from the loop start point. Can you guys fix it? I added ADX for comparison.

Here're the files:
https://mega.nz/#!ZWhRQKAQ!02z7973Yf0bnfmv0kle8n5iz6r6JAVMFzkD9OGpf2Gw

**Comment by bnnm** [comment]
Added a fix.

**Comment by mistersiraj11** [comment]
Cool! I'll wait for the new version. Thanks!
