### ISSUE TITLE
help sarch key

### ISSUE THREAD

**Issue by ponaromixxx** [losnoco/vgmstream#417]
Hello, please help me find the key for Okami HD or a tip how to find the keys!

**Comment by simontime** [comment]
Key for what, exactly?

**Comment by ponaromixxx** [comment]
.usm
https://mega.nz/#!j3QRSCqZ!_ADbB-ACQdCHGy6EYtyCqZF2LpWPwulG8624VPUYEqA

**Comment by ponaromixxx** [comment]
.adx: .adxkey (derived 6 byte key, in start/mult/add format)

What is it like?

**Comment by bnnm** [comment]
This has nothing to do with vgmstream so this kind of spam will get closed in the future.

Just this once though, unzip this near .usm files and run .bat: [demux-usm.zip](https://github.com/losnoco/vgmstream/files/3365866/demux-usm.zip)
