### ISSUE TITLE
did you notice anything odd with the way nub formats were implemented into vgmstream?

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#419]
i mean, take a look at this.
[nub_idsp.c](https://github.com/losnoco/vgmstream/blob/master/src/meta/nub_idsp.c)
[nub_vag.c](https://github.com/losnoco/vgmstream/blob/master/src/meta/nub_vag.c)
[nub_xma.c](https://github.com/losnoco/vgmstream/blob/master/src/meta/nub_xma.c)

you guys(or at least you bnnm) might be handling this whole .nub format the wrong way, especially if RIFF headers are involved(see Ridge Racer 6's .nub files if they exist) as .nub is supposed to be one big sound bank archival format that can store a lot of sound tracks depending on which codec said track was encoded into(at which point the header for each track has all the info available for the game to play said track - one example being the nub files from Tales of Vesperia Definitive Edition as each and every one of them contains all sound track headers containing all the info needed to play said track including the IS14 header data which is embedded right into the header, all of that followed by raw IS14 data themselves).

and yes, i know they *can* be extracted using some tool out there but i want to see vgmstream handling .nub files directly.

i just want to talk about this, nothing more, nothing less.

**Comment by bnnm** [comment]
I know this but it has low priority, since sound banks are time consuming to research and there doesn't seem to be much interest.

**Comment by AnonBaiter** [comment]
heh, can't disagree with that

**Comment by bnnm** [comment]
.nub now work.

**Comment by AnonBaiter** [comment]
groovy!

**Comment by AnonBaiter** [comment]
ohhh yikes, turns out the latest vgmstream's foobar2000 component update refuses to work with this MUSIC.nub file i have here at all.

said file is from Microsoft Windows version of Tales of Vesperia Definitive Edition, currently available on Steam. i can lend you that one file if you want.

**Comment by bnnm** [comment]
I'll need the file, yes.

**Comment by AnonBaiter** [comment]
hold on

**Comment by bnnm** [comment]
Should work now.

**Comment by AnonBaiter** [comment]
okay, so since i usually play these stuff through foobar2000's vgmstream component i don't really have the utmost capability to actually test if this latest update actually worked with the file i've just posted here for almost a week ago, thanks to the fact that i'm just stuck for said component to actually update.

but uh.... thanks for the fix i guess.

**Comment by bnnm** [comment]
The latest compilation is posted automatically here: https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts, and usually I only have time to work on this on weekends, no need for the passive-aggressiveness.

**Comment by AnonBaiter** [comment]
...right.
