### ISSUE TITLE
Another format to look into

### ISSUE THREAD

**Issue by kode54** [losnoco/vgmstream#420]
I was forwarded this link, it may or may not be interesting. Maybe I should look at it before linking to it here?

https://gbatemp.net/threads/help-converting-music-from-ckd-files.540172/#post-8664915

**Comment by bnnm** [comment]
Added this.

**Comment by kode54** [comment]
Reporting user, who does not have a Github account, inquired about looping. Apparently needs instruction on making these tracks loop from start to finish. I'll tell them what I know off hand, that it should be possible to set the player to Repeat Track.

**Comment by kode54** [comment]
Also, this file is reported to be among several that sound "corrupted" or incorrectly decoded. Most of them are sound effects.
[sfx_levelcomphighfive.wav.ckd.zip](https://github.com/losnoco/vgmstream/files/3286612/sfx_levelcomphighfive.wav.ckd.zip)

**Comment by bnnm** [comment]
Should be fixed.
.cdk don't have loop info, this user could try per-file looping with [TXTP](https://github.com/losnoco/vgmstream/blob/master/doc/TXTP.md#custom-play-settings), for example:

**music_giftshop.txtp**
```music_giftshop.wav.ckd#E```

**Comment by Danominator** [comment]
Hi. Sorry, I hate having to make new accounts for everything, but I'm the guy that's been annoying kode about this format. Most everything worked, I just don't know what's up with the sound effects. They sound kinda crunchy and far away. As far as the other stuff...

-I don't want to loop the sound effects, just fix the audio quality.

-I'm trying to convert the music files with 2 loops and a fade, and the settings in preferences>playback change nothing for some reason. Do I need a dsp plugin or another extension? I have vgmstream but changing those settings isn't making a difference.

Thanks for helping me with everything thus far, your guys' speed is incredible.

**Comment by kode54** [comment]
As suggested, you can create .txtp files with a text editor, named after the files you want to add loops to, with just that simple declaration inside them. Then the looping behavior will work.

**Comment by Danominator** [comment]
Quality is perfect now! And huh, it may be easier for me to convert and then loop in audacity. Thanks!
