### ISSUE TITLE
Possible issue with Wii DSP format

### ISSUE THREAD

**Issue by SamusAranX** [losnoco/vgmstream#422]
Long story short: I just ripped a few tracks from [Ultimate Board Game Collection](https://www.mobygames.com/game/ultimate-board-game-collection) for the Wii, but the files vgmstream gives me are glitchy, almost as if the file got jumbled and reassembled the wrong way.
Here's an example track:
[track04.zip](https://github.com/losnoco/vgmstream/files/3286363/track04.zip)

My extractor script basically just takes the game's flavor of .ARC archive and copies byte ranges into their own files, so I can't see it causing the problem.
That leaves the game itself (Maybe it reassembles the file parts at runtime? With how it's just shovelware, I can't imagine that happening though) and vgmstream.
Could you please verify that it's not vgmstream?

**Comment by bnnm** [comment]
vgmstream is probably setting a wrong interleave value, but unless you post a bunch of those extracted files (not wavs) it's impossible to say.

**Comment by SamusAranX** [comment]
I was certain I included the original file in the ZIP, my bad. It should be in this one:
[track04.zip](https://github.com/losnoco/vgmstream/files/3289434/track04.zip)

**Comment by bnnm** [comment]
For technical reasons that are tricky to fix I didn't add this directly.

Instead I've changed it (once it updates) so files don't play, and you can make a text file named *.dsp.txth* (notice it starts with a dot) and inside write:
```
codec = NGC_DSP
interleave = 0x10000

channels = 2
start_offset = 0x00

num_samples = @0x00:BE
sample_rate = @0x08:BE
loop_flag   = @0x0C:BE$2
sample_type = bytes
loop_start_sample = @0x10:BE
loop_end_sample   = @0x14:BE

coef_offset = 0x1c
coef_spacing = 0x10000
coef_endianness = BE
```
This will make files playable, but will start and sometimes end with a small glitch. Once I fix stuff I'll add direct support (so glitches are fixed and the .txth ignored).

**Comment by SamusAranX** [comment]
Tracks 1, 3, and 5 are pretty much perfect now (with small glitches that can easily be edited out), but tracks 2 and 4 are missing a good chunk of the right channel at the end.
Here's track 2, for example: 
<img width="1059" alt="Screenshot 2019-06-17 at 08 48 01" src="https://user-images.githubusercontent.com/676069/59583825-bd05f580-90dc-11e9-9569-3701837d7060.png">
Is there anything I can change in the TXTH file to avoid that?

**Comment by bnnm** [comment]
I think 2 and 4 are just missing 0x10000 bytes at the end, maybe recheck manually vs the .arc pack?
The header says how long (samples) the file is, but last data for right channel is missing, so you get that glitch.

**Comment by bnnm** [comment]
This now works directly, without the click at the beginning. Missing data is still probably an extraction error.

**Comment by SamusAranX** [comment]
For future reference: 
I finally got around to rechecking the original files and I'm certain it's not an extraction error. 
It looks like the original file is corrupt, as heard in this video at ~6:23: https://youtu.be/yJEmdpPDxwY?t=383

Another shovelware game mystery solved.
