### ISSUE TITLE
HD3+BD3 - Sony PS3 bank format , NOT sure how to do with vgm

### ISSUE THREAD

**Issue by EmirioBomb** [losnoco/vgmstream#429]
Hello, I have a file with P3HD header as following.
**test.pak**:  https://www.dropbox.com/s/vly3u0ivyp1ie12/test.pack?dl=0
Just as coded as hd3_bd3.c, it contained multi files( I don't know what format is)
<img width="416" alt="2" src="https://user-images.githubusercontent.com/27725119/59817399-45d99700-9352-11e9-9a87-da4ad8b3604f.png">
Then, I tried to use v**gmtoolbox / Sony ADPCM Extractor** to extract test.pak
However, I got some *.bin files that I don't know how to change ext or play them.
I think they're not regular format.

I checked **hd3_bd3.c** files, but I don't know how to use vgmstream exactly.
Could you help me how to extract P3HD or something useful advice?
Any help will be greatly appreciated!

**Comment by bnnm** [comment]
First you need to update vgmstream, since I fixed a related bug, then you need to split your file into test.hd3 and test.bd3.

Without programming knowledge this isn't simple, but basically the .hd3 goes from offset 0 to 0x640, and .bd3 is the rest of the file.

**Comment by EmirioBomb** [comment]
> First you need to update vgmstream, since I fixed a related bug, then you need to split your file into test.hd3 and test.bd3.
> 
> Without programming knowledge this isn't simple, but basically the .hd3 goes from offset 0 to 0x640, and .bd3 is the rest of the file.

Thanks for your prompt reply.

I can split test.pack to test.hd3 & test.bd3, and test.bd3 can be played by foobar with the latest vgmstream component.
Now, I can convert the test.bd3 to wav with foobar quickconvert option.

Would u like to help me how to convert bd3 to wav with all the subsongs ?
I don't know how to use <option> in test.exe!!
thank you so much !

**Comment by bnnm** [comment]
I think you are better using foobar to convert subsongs, but if you want to use test.exe and you know how windows command line you can save this to `test.bat` and put in with test.exe and your file:
```
set FILE=%1
set MAX=%2

for /L %%A in (1,1,%MAX%) do (
  test.exe -s %%A -o %FILE%_%%A.wav %FILE%
) 
```
Then call it with: `test.bat test.bd3 8`
