### ISSUE TITLE
BLiNX: the time sweeper and BLiNX 2: Masters of Time and Space sound format

### ISSUE THREAD

**Issue by BLiNXthetimesweeperGOD** [losnoco/vgmstream#430]
There are the easy to rip ADX/AIX files, but these games also have an odd sound format that uses a .bin (binary) extension and always starts with XSSB when opened in a hex editor. I opened them in Audacity as raw data and got a lot of static, but can hear the voices and other sounds through it. The start of the file seems to tell the game where each sound starts and ends and likely what the sound ID is from my experience messing around with them.
[Sound files.zip](https://github.com/losnoco/vgmstream/files/3315563/Sound.files.zip)

These came from the main ipk file of the BLiNX 2 trial demo

**Comment by bnnm** [comment]
The format isn't complex, I'll see if I can add it later.

**Comment by BLiNXthetimesweeperGOD** [comment]
Has any progress been made on this format yet?

**Comment by bnnm** [comment]
Added this. You may need to rename extensions to .lbin or set "enable common exts" in the plugin's options for the player to read the files though.
