### ISSUE TITLE
Super Mario Maker 2 "Pack" .bwavs aren't playing properly

### ISSUE THREAD

**Issue by mariomadproductions** [losnoco/vgmstream#441]
See the .bwavs in the .bars _Pack\StaticHighFreqSound.pack_

**Comment by bxaimc** [comment]
They seem to be playing fine on my end. Would you mind providing the BWAVs you’re having trouble with, please.

**Comment by bxaimc** [comment]
Actually, I notice there are some prefetch BWAVs in here that are incomplete versions. They will not play correctly and that’s normal since it relies on having a complete stream.
