### ISSUE TITLE
CLI build fails when FFmpeg is disabled

### ISSUE THREAD

**Issue by chz16** [losnoco/vgmstream#444]
I tried building the CLI player today (`make vgmstream_cli`) and the build died here:

```
gcc -Wall -Werror=format-security -Wdeclaration-after-statement -Wvla -O3 -DVAR_ARRAYS -I../ext_includes    -c -o coding/ffmpeg_decoder_custom_opus.o coding/ffmpeg_decoder_custom_opus.c
coding/ffmpeg_decoder_custom_opus.c:16:60: error: unknown type name 'opus_config'
static size_t make_oggs_first(uint8_t * buf, int buf_size, opus_config *cfg);
                                                           ^
coding/ffmpeg_decoder_custom_opus.c:233:66: error: unknown type name 'opus_config'
static STREAMFILE* setup_opus_streamfile(STREAMFILE *streamFile, opus_config *cfg, off_t stream_offset, size_t stream_size, opus_type_t type) {
                                                                 ^
coding/ffmpeg_decoder_custom_opus.c:408:61: error: unknown type name 'opus_config'
static size_t make_opus_header(uint8_t * buf, int buf_size, opus_config *cfg) {
                                                            ^
coding/ffmpeg_decoder_custom_opus.c:479:60: error: unknown type name 'opus_config'
static size_t make_oggs_first(uint8_t * buf, int buf_size, opus_config *cfg) {
                                                           ^
```

It looks like the problem is that the definition of `opus_config` in `src/coding/coding.h` is inside an `#ifdef VGM_USE_FFMPEG` block so it doesn't get defined if I'm not linking with FFmpeg (which I'm not), but those functions in `src/coding/ffmpeg_decoder_custom_opus.c` aren't so they're compiled no matter what.

I don't really know anything about the code here so I don't know if it'd be better to pull the definition of `opus_config` out of the `#ifdef` (I did this and it compiled fine), or to add more preprocessor guards to `src/coding/ffmpeg_decoder_custom_opus.c` or whatever.

I don't think my environment should matter here but in case you need to know: macOS 10.14.6 running Xcode 10.2.1's dev tools (clang 10.0.1)

**Comment by bnnm** [comment]
Should work now.

**Comment by chz16** [comment]
Yep, seems good now 👍
