### ISSUE TITLE
DOOM 3 BFG Edition (Windows) - idwav files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#448]
first of all, in order to not waste anyone's time i decided to upload only a "few" selected files here and there
[[doom_3_bfg_edition_windows]idwav_samples.zip](https://www.sendspace.com/file/tuqfef)

i first saw RAGE use a similar format like that, but that was back when i evilly had the PS3 and Xbox 360 versions of the game which had to be deleted into my external HDD 'cuz i was content in filling much of my HDD with stuff i wanted to store into said HDD... not to mention that RAGE itself uses an _awfully_ different way of storing sound formats(a .id[wav/msf/xma] file stored as a _separate file header_ in gameresources.resources and then either streamed.resources or should any language be involved [english/french/spanish/italian/german/japanese/russian/czech/polish].streamed and the file that's stored in either of these "streamed" files will be referenced in gameresources.resources no matter what so as to form a complete .id[wav/msf/xma] file) compared to DOOM 3 BFG Edition(in which .resources is just an file storage format and .id[wav/msf/xma] is just a standalone file).

**Comment by bnnm** [comment]
Added this.

**Comment by AnonBaiter** [comment]
groovy...
