### ISSUE TITLE
Making HCA/AFS2 decrypting work.

### ISSUE THREAD

**Issue by micktu** [losnoco/vgmstream#452]
So there've been another big case of using HCA subkeys: `Princess Connect: ReDive` got a full data refresh, and now all of it uses AWB scramble bytes.

What I wanted to ask is, why don't we read the bytes from the AWBs? why bother using tables? Is there anything that makes it hard?

And the last question, if you consider it doable, should I try to make it work?

Thanks.

*Edit:* The system right now is a bit confusing, so I thought it was not implemented. In fact I just stepped on a bug. You can disregard my original question.

**Comment by bnnm** [comment]
.awb with scramble keys work fine AFAIK since recently, for Dragalia Lost at least. The scramble table was left for convenience.

If your .awb aren't working it could be they changed the base/seed key too, and that needs to be added first.

**Comment by micktu** [comment]
There is in fact a problem with how it works right now.

`.hcakey`: real subkey works, 0 subkey (detection) does not work.
`example.awb.hcakey`: real subkey works, 0 subkey works.
In the code: not sure how to update the key, Dragalia key still refers to the tables you said is redundant. Have to look at the code to see how the subkey is formatted, so I can stick a zero in it.

**Comment by bnnm** [comment]
Not sure if I understand? 

When I play a .awb, the subkey is passed to the hca parser, so the table ([here](https://github.com/losnoco/vgmstream/blob/master/src/meta/hca_keys.h#L298)) is ignored and only its key is used. The table is only used if you extract the .hca from the .awb.

 If I remove Dragalia's subkey table, but leave the key in the list, the .awb plays fine (hca key is combined with the subkey). 

But if I remove the key and subkey table, and use a `.hcakey` (size 0x08), the .awb doesn't play as the key isn't correctly combined with the subkey, this is a bug I'll fix.

Your key file must be named `.hcakey` or `example.hcakey` btw.

Anyway, it would be easier if you post some samples and the keys you are trying to use. If Princess Connect uses a new key and you post it I'll update so you don't need the .hcakey though.

**Comment by micktu** [comment]
What I was trying to say it's bugged, is all. This is my case: https://github.com/micktu/priconner-bgm/blob/master/purikone.py

It works, but only if I provide .awb.hcakey with either correct or zero subkey (thus, length 10). It doesn't work if I provide length 10 .hcakey which is a bug, because there shouldn't be any difference.

The base key is the same. Just need to enable subkeys for it.
https://github.com/losnoco/vgmstream/blob/ed57b41e2111a13dd749ae6697cc8bed6f16f0bf/src/meta/hca_keys.h#L247

**Comment by bnnm** [comment]
I fixed external .hcakey (size 0x8) not combining with .awb's subkey correctly. Note that size 0x0a .hcakey will force that key+subkey and the awb's subkey will be ignored (by design).

**Comment by micktu** [comment]
Thank you!

Now it also works with the built-in key again.
