### ISSUE TITLE
Kingdom Hearts II .at3 files don't play at all

### ISSUE THREAD

**Issue by CartoonFan** [losnoco/vgmstream#465]
Hello. I'm running Linux and I've been trying to play the .at3 files from the Kingdom Hearts II set with vgmstream through various players: Audacious, foobar2000(with Wine), and the vgmstream123 program, and none have played the files successfully. I'm not 100% sure the issue is with vgmstream, as the set has some other issues, but I wanted to let you know just in case. Thanks!

**Comment by bnnm** [comment]
Those files are raw data without any info inside so you need to tell vgmstream how to play them.

Create a text file names ".at3.txth" in the folder (notice the starting dot) and paste this:
``` 
codec = ATRAC3
channels = 2
sample_rate = 48000
interleave = 0x180
num_samples = data_size
```

Or just unzip this file in the folder: [txth.zip](https://github.com/losnoco/vgmstream/files/3567070/txth.zip)

**Comment by CartoonFan** [comment]
Awesome, thanks a lot!
