### ISSUE TITLE
Rayman M (PS2) - borderline unplayable hxd files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#474]
okay, so the recent support for this .HXx sound format had me riled up for a while. since i've somehow managed to get the files for the PS2 version of Rayman M it was time for me to play these .hxd files on vgmstream through foobar2000 and just listen to all the music contained in these files to pass some time. as it turns out however, nothing worked for me with these files at all. sorry if i came out spiteful.

here are the files i've personally selected for this upload.
[[rayman_m_ps2]menubin_world_sound.7z](https://drive.google.com/open?id=1qGvqaD5iqsDKazsia5kLEl__BJRG2Ajd)

**Comment by bnnm** [comment]
Fixed.

**Comment by AnonBaiter** [comment]
look, i don't want to throw you off. i really don't.
foobar2000(using version 1.5 beta 16) refuses to deal with any and all .hxd files i can throw at with this vgmstream component installed. meaning the only place i can play these .hxd files at all is by using the command-line decoder for vgmstream at the moment. suffice to say these files work rather well with that "test.exe" executable.

**Comment by bnnm** [comment]
I added a fix for foobar.

**Comment by AnonBaiter** [comment]
thanks for the fix. now i can rest easy.
