### ISSUE TITLE
ext_libs source code?

### ISSUE THREAD

**Issue by NWPlayer123** [losnoco/vgmstream#475]
Would be nice to be able to compile the latest external libraries myself but I've never been able to find the source code (I assume it's not standard ffmpeg since it has -vgmstream)

**Comment by kode54** [comment]
There is an `ffmpeg_options.txt` supplied for the media-autobuild_suite, but I haven't been able to get that to work any more, so I need to supply a different build script for a different cross building suite I found, if I can find it again.

**Comment by bnnm** [comment]
If you check the [build guide](https://github.com/losnoco/vgmstream/blob/master/doc/BUILD.md#external-libraries) I describe how to compile them. I tested most of them myself using gcc.

[This](https://github.com/bnnm/vgmstream-ffmpeg) is how I compile ffmpeg when I need, though it wasn't updated to the latest options
