### ISSUE TITLE
Rockstar Games Presents Table Tennis (Wii) - unsupported .spd/.spt/.cue files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#486]
okay, so vgmstream support for spt+spd format is rather outdated now. considering there's this subsong feature that many supported formats seem to take advantage of, i though i need to help you guys out with this one.

[[rockstar_games_presents_table_tennis_wii]spd_spt_cue[two_banks_in_total].zip](https://drive.google.com/open?id=1GAVh_IcFMg4tw5Z0GMsgz0aIoFnayK2A)

exclusive to the Wii version of the game however is this .cue format that hangs out alongside spt+spd for whatever reason. the format itself acts as if it's accompanying these formats, and the structure itself isn't too easy to understand if you know what i mean. if you (or anyone else for that matter) need more .cue files like these let me know.

**Comment by bnnm** [comment]
Subsongs now work, not sure what the .cue is for though, wasn't needed.
