### ISSUE TITLE
Ni no Kuni Wrath of the White Witch Remastered (Windows 7) - unsupported sgd files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#489]
apparently the Windows version of this "Remastered" game uses Ogg Vorbis for its sound files(which use what is essentially a PS3-exclusive SGXD format possibly designed for internally made Sony games for... guess what, PS3). or something of the sort.

while .sgb/.sgh files from that version of the game play without a hitch(at a cost of displaying some sort of "wrong info" in regards to the "subsong" itself - vgmstream reports the bitrates of these .sgb files(if we take a "subsong" stored into said files into account) as 85(mono)-640(5.1)kbps when the actual bitrate for those are either 80(mono)-276(5.1)kbps in between), these .sgd files are an entirely different matter altogether. here's all of them.
[[ni_no_kuni_wrath_of_the_white_witch_remastered_win7]sgd.zip](https://drive.google.com/open?id=1rdHcljLZNHAXgKTV3RtMECmxfIfWdVmR)

**Comment by bnnm** [comment]
Added, note that some files have wrong sample rate but I think that's a cue feature of .sgd and can't fix, you can force rate with .txtp tho.
