### ISSUE TITLE
Psychonauts (Windows, 2005 release) - .icb/.isb files

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#497]
[[psychonauts_2005_pc_demo]icb_isb.zip](https://drive.google.com/open?id=1WW8clQBhhvFEZ-y13eFMVHvzEPqtExu_)
sorry, i just wanted to see this supported in vgmstream and all that.

**Comment by bnnm** [comment]
Added, the .icb looks like a cue file and is not needed but maybe you should keep it around if something useful is found later.

**Comment by AnonBaiter** [comment]
right...

**Comment by kode54** [comment]
I wasn’t even aware there was some container and/or cue files associated with this game. I just remember having two oggs per song, one intro and one loop. And some songs having two variations, like the camp theme and the camp night theme, each of which have separate bass guitar lead and harmonica lead versions.
