### ISSUE TITLE
Legend of Zelda - Twilight Princess AST files not playing correctly

### ISSUE THREAD

**Issue by Mohamed00** [losnoco/vgmstream#508]
Saw this on Twitter but thought I'd report it on here as well. I noticed that as of vgmstream r1050-2625-g02efa7d7, playback of AST files from The Legend of Zelda - Twilight Princess is broken. Every file I've tried so far produces a rather loud noise when playing. Example file: https://www.dropbox.com/s/pbd0b862iuqt7i5/demo19_01_b.ast?dl=1

**Comment by bnnm** [comment]
Should be fixed.

**Comment by Mohamed00** [comment]
Working now, thanks.
