### ISSUE TITLE
aax_utf.h and acb_utf.h look just about the same to me.

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#521]
so it's yet another codebase nitpick from me, this time it's about two .h files that cover the same `@UTF` format designed by CRI Middleware but uses two different approaches to each other to serve their respective formats(aax.c needs aax_utf.h and acb.c needs acb_utf.h, somehow)... even though these two .h files seem relatively similar to each other, one way or another.

some genuine feedback i'll try to get out of my chest out of this is, in a current state, to unite aax_utf.h and acb_utf.h into a stand-alone .h file so aax.c and acb.c can use that .h file instead of these two .c files finding themselves in a situation where they have to compete over who has the best `@UTF` implementation or something... consider this a "code optimization" kind of thing. or is there some sort of disadvantage that can prevent this from happening?

**Comment by bnnm** [comment]
You may have missed the "todo" [here](https://github.com/losnoco/vgmstream/blob/master/src/meta/acb_utf.h#L15).

acb_utf.h is intended to replace the aax_utf.h, as I fixed some bugs and tried to make a cleaner API, just that I need put some time to reimplement aax.c and decide where to put the UTF code.

**Comment by AnonBaiter** [comment]
uhh, i know that that todo line is there, i didn't mean to rush you into doing something so sudden. i'm not saying that "you should code more skillfully!" but i'm sorta feeling afraid that it was definitely the impression you've got out of this.

**Comment by bnnm** [comment]
I wasn't bothered or anything. Just pointing the issue is known (hence the todo) and still pending. I too want to make code as clear as possible, but only have so much time.
