### ISSUE TITLE
Tag fields with spaces in the name inaccessible through !tags.m3u

### ISSUE THREAD

**Issue by fincs** [losnoco/vgmstream#522]
While writing a tagset for a game, I came across the need to use the `ALBUM ARTIST` field name (differentiated from regular `ARTIST` which is different for at least one track), as listed in the [foobar2000 wiki](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mapping). Unfortunately it doesn't look like vgmstream's M3U parser provides any way to specify fields whose names contain spaces. I.e. this doesn't work:
```
# @ALBUM ARTIST Some artist
```
It would be helpful if a special syntax for escaping spaces could be added, such as `\ ` or perhaps just replacing `_` with a space internally.

**Comment by MDHEXT** [comment]
You use "# @ARTIST" and then for the album name you use "# @ALBUM". This issue is invalid.

**Comment by MDHEXT** [comment]
And yes, you do have to capitalize. So album is ALBUM and artist is ARTIST.

**Comment by fincs** [comment]
I wasn't talking about the album name. I was talking about the Artist vs Track Artist fields, which are different. I have music in my collection which has both fields, and with different content.

**Comment by CyberBotX** [comment]
> And yes, you do have to capitalize. So album is ALBUM and artist is ARTIST.

No, you don't. I have all my tags in !tags.m3u in lowercase and vgmstream doesn't care. Looking at src/plugin.c, it uses `strcasecmp` for that, the Winamp plugin in winamp/in_vgmstream.c uses that as well, I don't know about the internal of foobar2000 but I just loaded one of my files up and it shows the correct title and artist. The other two plugins (XMPlay and Audacious) don't seem to use the tags.

**Comment by bnnm** [comment]
Huh, didn't think players would use spaces, though now I see APEv2 tags and stuff allow them.

Because `_` is used in `replay_gain_x` and other tags and `\ ` escaping is a bit more involved
now it accepts `%TAG NAME%` for spaces ([see](https://github.com/losnoco/vgmstream/blob/master/README.md#tagging)). This breaks tags like `%TITLE 100%` which now must be `%TITLE% 100%`, and I hate breaking stuff, but hopefully those aren't too common.

Surprisingly foobar won't handle ALBUMARTIST in mp3/APEv2 (even though other players do), but it works for actual ogg. To increase interoperability I've added it as an alias for %ALBUM ARTIST%, so you could use @ALBUMARTIST if you plan to share the m3u.

**Comment by fincs** [comment]
Thank you very much, I will therefore use `@ALBUMARTIST` as suggested :)
I should have thought about the replaygain thing; my m3u in fact does have replaygain info. On a sidenote, it really was a pain to get the replaygain information inserted due to vgmstream tagging being read-only, and fb2k only supports saving replaygain info using tag updates. (I ended up having to write a script to parse the ListView window fb2k shows, which was kind of unpleasant...)

**Comment by bnnm** [comment]
Note that you force refresh tags by selecting files and *shift + right click > Tagging > Reload info from file(s)* (gets old too but better than nothing).

IIRC foobar only refreshes tags if the file itself has changed, and there is no way in the API to force a refresh, so I'm not sure write support would fix this annoyance. It happens too when you change default loop options and stuff.

**Comment by fincs** [comment]
I meant that foobar2000 can't write back the replaygain metadata to the txtp or m3u file because it's a read only format (and it makes sense for vgmstream to behave this way). fb2k does not provide any alternative way to save the calculated replaygain information.

And also, thank you very much for showing me how to force reload a file's metadata; that's something that annoyed me to no end when working with m3u/txtp and I'm glad there's a better solution than "disable library/delete playlist/close fb2k/open fb2k/add playlist again".
