### ISSUE TITLE
Amagami (PS2) .ahx

### ISSUE THREAD

**Issue by ghost** [losnoco/vgmstream#527]
[RIH0000.zip](https://github.com/losnoco/vgmstream/files/3927036/RIH0000.zip)
Hello everyone! I'm new here. And I'm reporting the first error.
The .ahx files sounds very distorted when it's playing.
Please, fix that.

**Comment by Mysticus92** [comment]
Please don't mind my ghost. That's actually secretly me,
Like I said before, The .ahx files sounds very distorted when it's playing.
Please, fix that.
[RIH0000.zip](https://github.com/losnoco/vgmstream/files/3928224/RIH0000.zip)

**Comment by bnnm** [comment]
Unzip this file in the ahx folder and it should play correctly:

[ahxkey.zip](https://github.com/losnoco/vgmstream/files/3928305/ahxkey.zip)

**Comment by Mysticus92** [comment]
Thank you! And sorry for this little confusion.

**Comment by Mysticus92** [comment]
Thank you!
