### ISSUE TITLE
acb_utf.h: rows can be 0

### ISSUE THREAD

**Issue by MustafaNesin** [losnoco/vgmstream#532]
Hi, I noticed the structure of the code is slightly different from the Pro Evolution Soccer file system.

The row count (rows field of utf_context) can be 0 when all column storages are zero, but the source code in acb_utf.h goes to fail label when this happens.

Example from PES 2013 (dt03.img>29th file>TBLCSB>TBLISC)

![Hex Dump](https://i.hizliresim.com/VQJdNv.png)

**Comment by bnnm** [comment]
I can allow 0 rows, but if you are interested in those sounds the format looks different from regular .acb (some early version called "csb"), so it'd need to be added.

**Comment by bnnm** [comment]
Fixed and added CSB, rename those files inside dt03.img to .csb to make them playable.
