### ISSUE TITLE
EA MGAV/DSPM - If the files lacked RVWS/SWVR info at the start, it will skips a few seconds from the start.

### ISSUE THREAD

**Issue by BloodRaynare** [losnoco/vgmstream#535]
I've been having this problem playing EA MGAV/DSPM audio stream inside of FLM videos I demuxed from GC version of Freekstyle (PS2 version has this problem too as well).

So basically, the audio stream has same format as the game's BGM, only differences is lack of RVWS/SWVR info at the start. However, it seems vgmstream is only playing from the second chunks onwards and ignore the first one causing vgmstream to skip few seconds from the start of the audio.

Here's a audio file sample from the demuxed FLM (eas_big.flm - EA Sports BIG logo - DSPM format)
[eas_big_gc.zip](https://github.com/losnoco/vgmstream/files/3965907/eas_big_gc.zip)
If it helps, here's the PS2 version as well (MGAV format)
[EAS_BIG_PS2.zip](https://github.com/losnoco/vgmstream/files/3965908/EAS_BIG_PS2.zip)

**Comment by bnnm** [comment]
Should be fixed.
