### ISSUE TITLE
dsp(Cstr) sorta needs a refresher.

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#540]
okay, sorry i opened up two issues 22-23 hours apart but i think it's time i need outside help once again.

so, i was on my way on implementing the most basic support for Namco's nuSound middleware. first, i'd managed to implement an entirely new meta for NXBF(wav extension) then i redid NPSF(nps extension) meta entirely. all with these two pesky files [here](https://www.sendspace.com/file/zw1tgu) through VS2019.

so i was on my way to implement Cstr(dsp extension) when suddenly i was met with a difficult challenge of passing of coefficients to vgmstream through the .h file, as well as trying to implement the rest of the Cstr "per-channel header" part after i've done all the work on laying out the Cstr "initial header" part "so well". right now i've just made the coef part as if it was just reading a coef per channel. [here's the updated nusound.h file by the way.](https://www.sendspace.com/file/gx1h8d)

sample files will come up much later. i need to bathe now.

**Comment by AnonBaiter** [comment]
okay i took a bath now. and i'm here to post some samples alongside my updated code regarding nusound.
to summarize, nusound.h has been renamed to nusound_stream.h and nusound.c has been change to accommodate this fact.

[here's said code by the way.](https://www.sendspace.com/file/x4qf1b)
[and the samples.](https://drive.google.com/open?id=1g0OB3j_aC8Vkm-9VKNs8OwM-CHwRkgH_)

**Comment by bnnm** [comment]
I'll take a look later and see what I can fuse but that seems a lot of complex parsing for such simple formats.

**Comment by AnonBaiter** [comment]
yeah i needed something easier to handle, that's how nusound_stream.h was born.

**Comment by bnnm** [comment]
I've cleaned up the Cstr meta, added NXBF to RIFF and doc NPSF. Even if the formats are part of the same engine they are different enough that it doesn't make sense to put them together, plus it's always better to keep them simple and only use complex structs for complex formats.
