### ISSUE TITLE
Shantae - Half-Genie Hero Glitchy output

### ISSUE THREAD

**Issue by Mohamed00** [losnoco/vgmstream#541]
Hi, I noticed that some FSB files from Shantae - Half-Genie Hero (PlayStation Vita) are producing rather glitchy output as of vgmstream r1050-2733-g000f0a72. Example: m_Boss_Final_FirstForm.fsb. https://www.dropbox.com/s/2yyem10vq3q99ez/m_Boss_Final_FirstForm.fsb?dl=1

**Comment by bnnm** [comment]
Should be fixed now.

**Comment by Mohamed00** [comment]
Working now, thanks.
