### ISSUE TITLE
[request] Dissidia Final Fantasy NT KWB2 .sed Format Support

### ISSUE THREAD

**Issue by healingbrew** [losnoco/vgmstream#546]
Dissidia Final Fantasy NT contains audio banks consisting of what seems like headerless Ogg Vorbis streams, I tried figuring some of the parts out but audio is a bit beyond me. It'd be great if vgmstream could support these files.

Some audio banks: https://mega.nz/#F!rJsE2KYT!LR1mUebfI_tNg4rTP1qpng

**Comment by bnnm** [comment]
This the later version of Koei's bank format, it's kinda complex so it will take a while. Codec is Microsoft ADPCM (frame size 0x16) though.

**Comment by healingbrew** [comment]
Oh that's interseting, I had no idea.

**Comment by healingbrew** [comment]
Are you sure the codec is MS ADPCM? I can't seem to get it to decode.

**Comment by bnnm** [comment]
Should work now.

**Comment by healingbrew** [comment]
Yep! Thank you so much :)
