### ISSUE TITLE
Cri Utf Column Type Correction

### ISSUE THREAD

**Issue by MustafaNesin** [losnoco/vgmstream#551]
According to CriAtomCraft source codes (I decompiled it with .NET Reflector) UTF column type enum must be like this;
![image](https://user-images.githubusercontent.com/33939581/72775989-92a38a00-3c21-11ea-8ba2-154c3469c123.png)

Namespace: CriMw.CriGears.Utilities
Class: Cbn
Enum: CbnFieldTypeNo

I was thinking sign prefixes could be opposite too, then I encountered this code and I decided to open this issue.  Also, this enum makes utf table values more sensible in PES game files.

Sorry for my English, I wish I could clearly state the situation.

**Comment by bnnm** [comment]
Thanks, you are right. They do use 16b to store sample rate in ACBs, and that only makes sense as unsigned, guess I wasn't paying attention (not sure if they ever use signeds actually).

I've fixed this and tweaked flag behavior based on decompilation too.

**Comment by MustafaNesin** [comment]
Yes, they use signed integers for pitch values (int16) and some other things in PES 2013. I didn't check other series yet.
