### ISSUE TITLE
Trouble Loading

### ISSUE THREAD

**Issue by XaikuTheMaverickHunter** [losnoco/vgmstream#554]
As of I the time I write this, I have just attempted to play an .at9 file, but this caused Winamp to hang. Is there any way to circumvent this?

**Comment by XaikuTheMaverickHunter** [comment]
This seems to only happen with these types of files and those related to them, but I'm not sure.

**Comment by kode54** [comment]
Please post a game name and file name, or if the file isn't from a vgm.hcs64.com public rip, zip up a file and upload it to this issue.

**Comment by XaikuTheMaverickHunter** [comment]
Never mind. I just needed to update the plugin again.
