### ISSUE TITLE
Electronic Arts BNK header/Electronic Arts MicroTalk Only Converts 1 Sound

### ISSUE THREAD

**Issue by kim-sama** [losnoco/vgmstream#559]
I'm trying to convert .bnk files from EA games. PSound can get only get some but vgmstream can find all of them, but only one. It should get all of them like .mus files

Here is the file: https://mega.nz/#!19MB0SAS!zrcWomRAtRF6UG4R1QbyEIcpMMUbGCPRafvqDNXmbFg

What it truned out: https://mega.nz/#!40VFFQaa!TWVIL3Vk6Ompk3g1UqXAJ9xY3In9Klz_Opr0_rWWTik

**Comment by NicknineTheEagle** [comment]
I don't quite understand what the problem is. What do you mean by "all of them, but only one" and "should get all of them like .mus files"?

**Comment by kim-sama** [comment]
When I open the file on PSound it finds a bunch of sounds but vgmstream only converts 1 of them and not all of the sounds in 1 wav
![image](https://user-images.githubusercontent.com/40289574/74602602-90d4c580-50fe-11ea-8060-e1d64c66f4a5.png)

**Comment by NicknineTheEagle** [comment]
Oh, are you using test.exe? It supports subsongs but handling them through that tool is a chore. Use one of the player plugin versions, it'll add all subsongs as separate tracks: 
![image](https://user-images.githubusercontent.com/6665256/74602656-11260700-50bc-11ea-8a51-66c12662e91d.png)

**Comment by kim-sama** [comment]
Oh, it works, thanks
