### ISSUE TITLE
nub format - "dsp" variant

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#562]
i'm not going into too much detail aside from the fact that vgmstream is missing one codec out of the nub/nus2 format.
[se_matsuri_10_a.nub](https://drive.google.com/open?id=1j9PQ6NnHbgnOrColEPQYbgwRmFak6-pr)

what i'm going to say though is that the "dsp" header seems to use standard Nintendo DSP header structure, i guess...

the name of the game in which i got this file from is **_Taiko no Tatsujin Wii Chou Goukanban_**.

**Comment by bnnm** [comment]
Should work now.
