### ISSUE TITLE
Is FDK-AAC/QAAC still needed? Because it doesn't quite work right on non-Windows systems

### ISSUE THREAD

**Issue by andlabs** [losnoco/vgmstream#569]
I'm trying to build vgmstream as a static library for a personal project, and I'm running into several hurdles if I choose to enable FDK-AAC/QAAC support.

The `cmake` configuration I am using is:

```
$ # in pwd:
_prefix/ build/ vgmstream/ fdk-aac/ qaac/
$ cmake -B build -S vgmstream \
> '-DCMAKE_SYSTEM_PREFIX_PATH=/usr;/usr/local' \
> -DCMAKE_INSTALL_PREFIX=$PWD/_prefix \
> -DFDK_AAC_PATH=$PWD/fdk-aac -DQAAC_PATH=$PWD/qaac \
> -DBUILD_CLI=OFF -DBUILD_AUDACIOUS=OFF \
> -DCMAKE_IGNORE_PATH='/opt/local/bin;/opt/local/include;/opt/local/lib'
```

After determining that I needed to point FDK_AAC_PATH and QAAC_PATH to *source* archives *without* building them ahead of time (which the documentation does not make clear), I can try building. However, I get different insurmountable build errors each time:

With kode54's forks of both fdk-aac and qaac:

```
$ cmake --build build
...
[  1%] Building CXX object CMakeFiles/mp4v2.dir/$PWD/qaac/mp4v2/src/3gp.cpp.o
In file included from $PWD/qaac/mp4v2/src/3gp.cpp:28:
In file included from $PWD/qaac/mp4v2/src/impl.h:6:
In file included from $PWD/qaac/mp4v2/src/src.h:28:
$PWD/qaac/mp4v2/src/mp4util.h:36:51: error: 
      invalid suffix on literal; C++11 requires a space between literal and
      identifier [-Wreserved-user-defined-literal]
            throw new Exception("assert failure: "LIBMPV42_STRINGIFY((ex...
                                                  ^
                                                   
1 error generated.
make[2]: *** [CMakeFiles/mp4v2.dir/$PWD/qaac/mp4v2/src/3gp.cpp.o] Error 1
make[1]: *** [CMakeFiles/mp4v2.dir/all] Error 2
make: *** [all] Error 2
```

This happens even with `-DCMAKE_CXX_STANDARD=14` or `-DCMAKE_CXX_EXTENISONS=ON` or both.

With upstream fdk-aac (by mstorsjo) and qaac (by nu774):

```
$ cmake --build build
...
[ 10%] Building CXX object CMakeFiles/mp4v2.dir/$PWD/qaac/mp4v2/src/mp4.cpp.o
$PWD/qaac/mp4v2/src/mp4.cpp:899:20: error: 
      cannot initialize return object of type 'mp4v2_ismacrypParams *' (aka
      'mp4v2_ismacryp_session_params *') with an rvalue of type 'MP4TrackId'
      (aka 'unsigned int')
            return MP4_INVALID_TRACK_ID;
                   ^~~~~~~~~~~~~~~~~~~~
$PWD/qaac/mp4v2/include/mp4v2/general.h:49:33: note: 
      expanded from macro 'MP4_INVALID_TRACK_ID'
#define MP4_INVALID_TRACK_ID    ((MP4TrackId)0)       /**< Constant: inv...
                                ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/mp4v2.dir/$PWD/qaac/mp4v2/src/mp4.cpp.o] Error 1
make[1]: *** [CMakeFiles/mp4v2.dir/all] Error 2
make: *** [all] Error 2
```

My system is  macOS 10.12.6, with Xcode 9.2 (9C40b) from Apple and cmake version 3.16.4 from MacPorts.

However, when talking with kode54 about these errors, they urged me to open this issue, because:

```
[20:50:43]  <kode54>	open an issue on vgmstream repo, asking to delete qaac/fdk-aac completely and replace with ffmpeg
[20:50:48]  <kode54>	there's literally only one format I added it for
[20:51:13]  <kode54>	it was a CAF that contained an AAC stream in a plain MPEG-4 container
[20:51:41]  <kode54>	this was before FFmpeg support was added
```

And I would tend to agree with this, on two grounds:

1. ffmpeg can be built with FDK-AAC support, if you really want to use the Fraunhofer code. However, from what I can gather, this is only for *encoding*, which isn't what vgmstream is for, right? Either way, ffmpeg should now support *decoding* everything supported by both FDK-AAC and QAAC, including that weird containered file that I don't know what it is.
2. QAAC appears to be strictly Windows only, despite the vgmstream documentation implying otherwise (since it does not list USE_FDKAAC as Windows only and says both FDK-AAC and QAAC have to be used together). Some of these errors appear to be MSVC-isms?

But that's just my take, which is possibly ill-informed.

**Comment by richardpl** [comment]
FDK-AAC have decoder for xhe-aac, but i doubt games use that stuff already.

**Comment by andlabs** [comment]
Even then, fdk-aac is portable and can be used directly. Not sure about QAAC — does QAAC provide anything that neither FDK-AAC nor fmpeg provide?

**Comment by bnnm** [comment]
You can safely disable FDK-AAC/QAAC in your build, FFmpeg will be used to decode all formats needing AAC.

In fact I have never built with them using GCC, most formats using AAC are only implemented with FFmpeg and not FDK-AAC/QAAC anyway.

I'm not aware what (if any) are the advantages of FDK-AAC+QAAC vs FFmpeg for vgmstream, I figured kode54 kept it around for some particular reason.

**Comment by andlabs** [comment]
Right, but that just reinforces my question — is there something that QAAC provides that ffmpeg doesn't? We can either use FDK-AAC directly as a library or just have ffmpeg use it directly instead, but that only handles half of the equation.

**Comment by bnnm** [comment]
Well, vgmstream uses them if both VGM_USE_MP4V2 (QAAC) and VGM_USE_FDKAAC (FDK-AAC) flags are enabled, or FFmpeg if either one is disabled.

I think QAAC is used to parse .mp4 (file format), while FDK-AAC for AAC decoding (actual codec), but you can disable them as code using FFmpeg (that does both) takes over.

**Comment by kode54** [comment]
Yes, but there is at least one case that uses QAAC/FDK-AAC for MP4 handling, but doesn't appear to have a fallback for FFmpeg.

init_vgmstream_akb_mp4 ... hmm, this appears to be the only one.

**Comment by bnnm** [comment]
If does have a fallback, right below as init_vgmstream_akb

**Comment by kode54** [comment]
I see that other function doesn't even do basic checking on the header, such as the offset to the audio data. It is hard coded to assume a header size of 32 bytes. It also doesn't check the codec field, assuming there is one in that format it's supporting.

Minor aside on the FDK-AAC/QAAC thing. I only picked QAAC because it contained a recent and maintained copy of libmp4v2. Alternately, I could have picked mp4ff or something similar, if I felt like reading up on how to use them. Also, FDK-AAC v2 and newer, which is not the version I stupidly forked and messed with, also supports xHE-AAC decoding, in case that's ever relevant.

**Comment by bnnm** [comment]
MSVC and CMake now don't set these flags by default (code is still around just in case).
