### ISSUE TITLE
(feature request) TXTP external file referencing support

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#575]
okay, so first of all i'd like to request... this.

TXTP could have some sort of "external file referencing" feature, which could be used on formats that depend heavily upon other files but have zero references to any of these files within said formats. this gets extremely problematic when the two files who actually have any sort of relation to each other at all have extremely different filenames (see below for an example of this).

for one example of this, the MPF format used in some EA games could benefit from this feature in a lot of ways. the MPF format has been designed to contain an external link to an MUS file without making it obvious in its MPF format that it's actually doing so, which means that external linking can be done like this.

**Medal of Honor - Frontline (Xbox)**
```
1_1M.mpf
target_stream = main.mus # assign external file to 1_1M.mpf
```

as you can see, the filenames for both the mpf and mus file can be quite different from each other despite 1_1M.mpf being a "map file" to main.mus.

[barring some intense work-arounds with the mpf format itself](https://github.com/losnoco/vgmstream/blob/master/src/meta/ea_schl.c#L625-L731), this could actually come in handy for situations when a "map file" has no reference whatsoever to an "external file" despite clearly being designed to be so.

as for a "map file" that is designed to support tons of sound entries without a single reference to any of them, this can be quite a nightmare. the .srt and .ssd file formats as used in (from my knowledge) **Takarajima Z/Zack and Wiki** and two **Tatsunoko vs. Capcom** games require _a lot_ of external linking to each other and it gets painful real fast, particularly so as the games themselves have all the references to .ssd files it needs to link these said files into .srt files, either through some obscure file that's being called by the game or through the executable itself, which contains most of the work needed to run the game on an machine it's been designed for.

either way, for the .srt and .ssd files it could be done like this.
**Takarajima Z - Barbaros no Hihou/Zack & Wiki: Quest for Barbaros' Treasure (Wii)**
```
bgm_S01.srt
target_stream = st_s01_00a.ssd#0 # assign st_s01_00a.ssd as subsong 0 of bgm_S01.srt
target_stream = st_s01_00b.ssd#1 # ditto for subsong 1
target_stream = st_s01_00c.ssd#2 # ditto for subsong 2
target_stream = st_s01_01a.ssd#3 # ditto for subsong 3
target_stream = st_s01_01b.ssd#4 # ditto for subsong 4
target_stream = st_s01_02a.ssd#5 # ditto for subsong 5
target_stream = st_s01_02b.ssd#6 # ditto for subsong 6
target_stream = st_s01_02c.ssd#7 # this is literally how the srt format works, you're missing nothing here.
```

this feature could also be useful for situations where you have a sound bank file alongside a sequenced midi-like file. something like this.

**Midnight Club II (PS2)**
```
airport3d.bd # .bd file requires an .hd file of the same name
target_sequence = airport3d.sq
```
```
dogs_cat.bd # .bd file requires an .hd file of the same name
target_sequence = dogs_cat1.sq
```
**The Bouncer (PS2)**
```
menu.wd # single sound bank
target_sequence = menu.bgm
```

of course, none of these files (aside from mpf and mus) are supported as far as i'm concerned, but i'm just doing this so i can at least try to think ahead here.

that's it for me though. the way i'm seeing it is that for whatever problems you may want to find with this feature, it has a lot of potential to be eventually useful in the long run.

**Comment by bnnm** [comment]
That is generally possible with TXTH, except MPF which is a bit strange/complex.

See [info](https://github.com/losnoco/vgmstream/blob/master/doc/TXTH.md#headerbody-settings), also check examples like "Grandia", "Simple 2000 Series Vol. 120 - The Saigo no Nihonhei ", "Shikigami no Shiro - Nanayozuki Gensoukyoku" towards the end.

**Comment by AnonBaiter** [comment]
this should be good enough.

**Comment by AnonBaiter** [comment]
so i tried to do a txth out of some .srt file as used on the Zack and Wiki game (while keeping game directory structure intact) and failed miserably.

[txth_failure](https://drive.google.com/open?id=1C-5Ilj63HaxBwBUDEwdlzdWdw8CIaP7R)
(google drive lets you download the whole folder as a zip file)

the filenames you see on bgm_s01.list were taken from main.dol of the game without any changes whatsoever.

**Comment by bnnm** [comment]
First update, as I fixed some edge cases.

Then, you can't set subsongs with separate streams (subsongs are only for bigfiles). Instead you can make and open a .txth per file:

**Zack & Wiki (Wii) st_s01_00a.txth**
```
#alt from above with untouched folders
header_file = Sound/BGM/bgm_S01.srt
body_file = snd/stream/st_s01_00a.ssd
name_table = .names.txt

base_offset = @0x0c:BE
base_offset = base_offset + @0x08:BE + name_value
base_offset = base_offset + @0x00:BE

codec = NGC_DSP
channels = 2
interleave = half_size
sample_rate = @0x08:BE
loop_flag = @0x04:BE

sample_type = bytes
loop_start_sample = @0x10:BE
loop_end_sample = @0x14:BE
num_samples = @0x18:BE

coef_offset = 0x20
coef_spacing = 0x40
coef_endianness = BE
```
*.names.txt*
```
*snd/stream/st_s01_00a.ssd: 0*0x04
*snd/stream/st_s01_00b.ssd: 1*0x04
*snd/stream/st_s01_00c.ssd: 2*0x04
*snd/stream/st_s01_01a.ssd: 3*0x04
*snd/stream/st_s01_01b.ssd: 4*0x04
*snd/stream/st_s01_02a.ssd: 5*0x04
*snd/stream/st_s01_02b.ssd: 6*0x04
*snd/stream/st_s01_02c.ssd: 7*0x04
# uses wildcards for full paths from plugins
```

Or more more naturally put the .srt, .ssd and .ssd.txth together and open .ssd:


**Zack & Wiki (Wii) .ssd.txth**
```
header_file = bgm_S01.srt
name_table = .names.txt

base_offset = @0x0c:BE
base_offset = base_offset + @0x08:BE + name_value
base_offset = base_offset + @0x00:BE

codec = NGC_DSP
channels = 2
interleave = half_size
sample_rate = @0x08:BE
loop_flag = @0x04:BE

sample_type = bytes
loop_start_sample = @0x10:BE
loop_end_sample = @0x14:BE
num_samples = @0x18:BE

coef_offset = 0x20
coef_spacing = 0x40
coef_endianness = BE
```
*.names.txt*
```
st_s01_00a.ssd: 0*0x04
st_s01_00b.ssd: 1*0x04
st_s01_00c.ssd: 2*0x04
st_s01_01a.ssd: 3*0x04
st_s01_01b.ssd: 4*0x04
st_s01_02a.ssd: 5*0x04
st_s01_02b.ssd: 6*0x04
st_s01_02c.ssd: 7*0x04
```

**Comment by AnonBaiter** [comment]
okay, i'll test the new update and see what happens.

**Comment by bnnm** [comment]
I forgot to adjust `base_offset` for other songs, fixed .txth in the above post, all songs seem fine for me in both cases. Note that st_s01_00a and st_s01_01b are the same file, and that you can use any .txth name in the first example.

**Comment by AnonBaiter** [comment]
okay, i can safely report that only the .ssd.txth part works now.

> Note that st_s01_00a and st_s01_01b are the same file, and that you can use any .txth name in the first example.

noted (in fact i tried st_s01_01b with that first example and it worked), though the first example doesn't seem to work too well for other files. st_s00_00b in particular still sticks with that num_samples value st_s01_00a has no matter what i do (placing `+ base_offset` after the sample_rate, loop_flag, loop_start_sample, loop_end_sample, num_samples values or even before them doesn't seem to do much).

**Comment by bnnm** [comment]
They all work for me in foobar/winamp/test with corect samples/etc: [txth-open.zip](https://github.com/losnoco/vgmstream/files/4334468/txth-open.zip)

**Comment by AnonBaiter** [comment]
tested these txth files with latest vgmstream (windows) build (the "test" one, version r1050-2870-g50cb9422), again obtained through appveyor. and i get this for every txth file i pass off to test.exe with -i parameter enabled.
```
loop start: 819210 samples (0:18.576 seconds)
loop end: 4195884 samples (1:35.145 seconds)
stream total samples: 4195884 (1:35.145 seconds)
samples to play: 4195884 (1:35.145 seconds)
```
every other file aside from st_s01_00a and st_s01_01b doesn't seem to have these four values changed at all. st_s01_00c in particular suffers from frequent glitching as playback goes on and then there is sudden silence, yet despite this i checked interleave size as reported by test.exe against st_s01_00c.ssd and said size is correct so i don't know what's going on in my end.

**Comment by bnnm** [comment]
With test r1050-2870-g50cb9422 from [here](https://ci.appveyor.com/api/buildjobs/arwgwyea6cp1fu79/artifacts/Release%2Ftest.zip) (as well as my own compilations) I get normal results:

`test.exe -i st_s01_00a.txth`
```
decoding st_s01_00a.txth
sample rate: 44100 Hz
channels: 2
looping: disabled
loop start: 819210 samples (0:18.576 seconds)
loop end: 4195884 samples (1:35.145 seconds)
stream total samples: 4195884 (1:35.145 seconds)
encoding: Nintendo DSP 4-bit ADPCM
layout: interleave
interleave: 0x2495e0 bytes
metadata from: TXTH generic header
bitrate: 403 kbps
samples to play: 4195884 (1:35.145 seconds)
```

`test.exe -i st_s01_00b.txth`
```
decoding st_s01_00b.txth
sample rate: 44100 Hz
channels: 2
looping: disabled
loop start: 2575356 samples (0:58.398 seconds)
loop end: 7205856 samples (2:43.398 seconds)
stream total samples: 7205856 (2:43.398 seconds)
encoding: Nintendo DSP 4-bit ADPCM
layout: interleave
interleave: 0x3ed4a0 bytes
metadata from: TXTH generic header
bitrate: 403 kbps
samples to play: 7205856 (2:43.398 seconds)
```

etc.


Maybe try setting the name list without paths (normally just needs names):
```
st_s01_00a.ssd: 0*0x04
st_s01_00b.ssd: 1*0x04
st_s01_00c.ssd: 2*0x04
...
```

Or moving the files to another folder, or making sure you didn't overwrite the .srt file with other thing, I just used those uploaded files as is.

**Comment by AnonBaiter** [comment]
i tried to do something like this without moving anything to any folder whatsoever.
```
*st_s01_00a.ssd: 0*0x04
*st_s01_00b.ssd: 1*0x04
*st_s01_00c.ssd: 2*0x04
...
```
it worked this time around.
