### ISSUE TITLE
Nus3Audio parser needs updating?

### ISSUE THREAD

**Issue by Tenome** [losnoco/vgmstream#578]
From what I understand, Nus3Audio is just a container for OPUS audio and I guess technically shouldn't be supported. However, since it looks like you added a parser to VGMStream (nus3audio.c), I just thought I should let you know that it appears that the format has changed a bit. I tried [extracting](https://github.com/jam1garner/nus3audio) a recent nus3audio file from Smash Bros. Ultimate v.7.0 released in January or so, and it no longer extracts like 1.0 does.

Sample nus3audio files from Smash Ultimate:
1.0: https://z.zz.ht/iKg0V.nus3audio
7.0: https://z.zz.ht/xvVFD.nus3audio

**Comment by bnnm** [comment]
That 7.0 file looks incorrectly extracted/decrypted, it's a bunch of garbage data with no OPUS.

There is nothing wrong about supporting containers. If it's some audio-looking file that one would try to open with vgmstream then it's a candidate for support (the less tools and bms I have to hunt down to play stuff the better). Technically nus3audio's OPUS never exists as an external file, so it's kinda weird to extract it, even.

**Comment by Tenome** [comment]
Weird, maybe the file got messed up because I went straight to patch 7.0 rather than updating in increments (I followed the same procedure otherwise). I'll try again later.

**Comment by Tenome** [comment]
It was a problem on my end with how I patched it, oops.
