### ISSUE TITLE
New(?) slightly updated version of CRI ADX audio format

### ISSUE THREAD

**Issue by DeathChaos25** [losnoco/vgmstream#584]
Upon some inspection the format header seems unchanged?

However at 0x13 the version seems to indicate 9, changing it to 0 makes the file "work" but when it plays back it will destroy your ears for a lack of better words, seems there was some sort of format change?

Attached sample files of this new version;
[be_boss_0217.zip](https://github.com/losnoco/vgmstream/files/4430992/be_boss_0217.zip)

**Comment by bxaimc** [comment]
It just needs a key to decrypt the files. We’ll add it later for P5R.

**Comment by bxaimc** [comment]
Added #585 Release will happen soon after.
