### ISSUE TITLE
FIFA/FIFA Manager audio files - SCHl (.ast, .abk, .dat, .hdr)

### ISSUE THREAD

**Issue by vergol** [losnoco/vgmstream#589]
FIFA/FIFA Manager games (old ones, 07, 08 and so on) use some different "variations" of SCHl file format - these files are very similar to .ASF files and most of them can be decoded with vgmstream, if you rename the extension to .ASF.

**.AST** : all files can be decoded. As I understood, files may consist of multiple sounds. Some sounds are exported and merged into .WAV with vgmstream. Some are probably ignored (or they are empty?). Some artifacts are present in resulting file, right between different sounds (or at file beginning).

**.ABK** : duplicates of .ast, but smaller file size. Most of files can be extracted with vgmstream. Some files are not extracted (playercalls00.abk, EndMatch_Whistles.abk).

**.HDR/.DAT** (header+data?): commentary files. DAT files can be extracted when renamed to ASF. Similar to AST/ABK (multiple sounds and related problems).

Maybe you could check files:
Overview: https://mega.nz/file/v5EjCAaQ#IGJkXScNQnm6_8Tky_Fz7LtTjwcVxBcqQNDGp0qHRmk
AST: https://mega.nz/file/agFm1IjZ#27ncGOI456WOx_pIc5lS5C90xKS4-2E7w-zmSd9D4-c
ABK: https://mega.nz/file/SxNgnCpC#roOE0uA7r0wjSmIVCSCg1yGBEL7Yv16pTxJ6iT-53YA
HDR/DAT: https://mega.nz/file/rxNhBCza#doo_QhtCOAU0eqzTpb9i8XUxiE2eK4wvZSDCRmzVApg

**Comment by NicknineTheEagle** [comment]
These are aren't "variations", they're various soundbank formats used by EA.
AST is a companion file of ABK. Put AST together with ABK and then open ABK file.
HDR/DAT is a bank format commonly used for storing speech. Open HDR file and you'll get the sounds.
If you're using test.exe, use a player plug-in instead since test.exe only converts one subsong at a time.

**Comment by NicknineTheEagle** [comment]
Hmm, vgmstream fails to open HDR files, looks like I'll need to fix the parser.

**Comment by NicknineTheEagle** [comment]
https://github.com/losnoco/vgmstream/pull/590

**Comment by vergol** [comment]
Now I used Winamp plugin and it worked with ABK/AST.
Waiting for the binary release with HDR/DAT fix.
Thank you.
