### ISSUE TITLE
genh (Xbox) audio file is converted with no audio in recent vgmstream?

### ISSUE THREAD

**Issue by Tenome** [losnoco/vgmstream#596]
vgmstream CLI decoder r1050-2861-g126e3b41 Mar  9 2020

Source file:
00000013.genh
https://z.zz.ht/NoN4H.genh

Procedure:
CMD > test.exe 00000013.genh
VGMStream seems to work as normal: https://puu.sh/Fxi0R/8d36cb33d8.png

Result:
00000013.genh.wav
https://z.zz.ht/gkJqd.wav
No audio

Expected Result (achieved using the GUI wrapper [VGSC](https://www.vg-resource.com/thread-25478.html) which says it's using vgmstream r1040):
00000013.wav
https://z.zz.ht/prqae.wav
Audio plays as normal
VGMStream seems to work as normal: https://puu.sh/Fxi86/7f91675397.png

Any idea where the error occurred that might've gutted the audio in the standalone CMD attempt?

Edit: Same problem with vgmstream CLI decoder r1050-2410-gead9ec4f-490-g8638b219 Apr 11 2020 as well.

**Comment by bnnm** [comment]
Fixed, see https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts

That GENH is kinda buggy though.

**Comment by Tenome** [comment]
Thank you!
