### ISSUE TITLE
Gundam Versus PS4 - nus3audio

### ISSUE THREAD

**Issue by 09williamsad** [losnoco/vgmstream#602]
The nus3audio container from Gundam Versus appears simular to the SSBU container but vgmstream fails to open or extract it

Samples https://mega.nz/folder/DfpVGIyY#Y8y3JPlOtgjmVixDN40zuw

jam1garner's nus3audio tool can read the files but not extract.
https://github.com/jam1garner/nus3audio

**Comment by bnnm** [comment]
Works in latest version.

https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts
