### ISSUE TITLE
Honkai and Genshin Wise Sounds

### ISSUE THREAD

**Issue by FilipeKun** [losnoco/vgmstream#604]
So after i got 18/04/2020 f2k component update, i was hyped due Genshin Wwise files would be playable with this plugin (since i was having difficulty for convert them to ogg due them having PTADPCM codec), so i went to try it and got this error:
> Unable to open item for playback (Missing ACM codec)

I've also tried to research something about it and nothing (even installing a ACM plugin).

As for the honkai files they give me this error when i try to play them (they're 0xfffff codec):
> Unable to open item for playback (Unsupported format or corrupted file):

for extract them i used a wavescan.bms by AlphaTwentyThree :\ idk if i'm doing something wrong or if the plugin isn't working.

Note for honkai files - by using Wwise-unpacker-master and converting them to ogg allow me to play it but by doing the above way i did which is just wavescan (leaving it as .wav) gives that error.

**Comment by kode54** [comment]
This plugin will not take priority over the player’s built in `.wav` player unless you move it higher in the input listing, which is not advised. It is preferred to rename your files to a “fake” extension supported by the plugin alone, like `.lwav` or `.vgmstream`.
