### ISSUE TITLE
Punch-Out!! (Wii) audio file distortions?

### ISSUE THREAD

**Issue by Mysteryman951** [losnoco/vgmstream#605]
Most audio files work fine, but there are a few that sound distorted.

https://www.youtube.com/watch?v=zoSlZAQJ6jc

The first sound effect is an example of a distorted clip with its corresponding properties while the second is a sound effect working just fine, also with its properties. If any more info from foobar itself might be needed to help fix this please let me know :)

I didn't play the distorted sound twice btw, all of them tend to repeat for some reason. The common differences between the distorted and undistorted files seem to be a channel mask of 0x3 / FL FR for distorted and 0x4 FC for undistorted. Distorted files also have an interleave of 0x8 while undistorted files don't have any mention of interleaving. I'm not sure if this is true for every single case but it seems quite likely.

**Comment by bnnm** [comment]
Try latest: https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts

Those files should come from .bnk, and if you play the .bnk they'll be fine. If you extract the subsongs they may not be detected correctly, though maybe you can force by changing extractions' extension to .bnk.

**Comment by Mysteryman951** [comment]
Hi again, thanks a bunch. The newest version removes the issue of the double speed and distortion. However, a significant amount of the files now have a loud static in either the latter half or full duration of their length, even when coming directly from the bnk? Thanks again.

**Comment by bnnm** [comment]
Should work now.
