### ISSUE TITLE
Gitaroo Man IMC has more sample rates than allowed by vgmstream

### ISSUE THREAD

**Issue by boringhexi** [losnoco/vgmstream#606]
[This line](https://github.com/losnoco/vgmstream/blob/afecc953f39f6666c493797b0683119046f840a8/src/meta/imc.c#L27) in vgmstream restricts Gitaroo Man IMC sample rates to the range [22000, 48000].

Today I did some investigating and found that the full list of allowed sample rates is: 11025, 16000, 22050, 32000, 44100, 48000. Anything besides those will result in silent audio in-game. (Specifically, the game's mstream.irx's CalculatePitchRate function checks specifically for those six values. It returns 0 if it's not one of those, resulting in silent audio.)

~~I'd open a pull request (my first ever!), except I'm not sure whether to restrict to the range [11025, 48000] or just those 6 specific values.~~ Pull https://github.com/losnoco/vgmstream/pull/607 request created, it only allows those 6 specific values.

**Comment by bnnm** [comment]
I think either way (ranges or exact values) is fine. It gets boring to code too specific values though, so just adding a comment would be ok too, the validation is there just in case.

Do note ST10.IMC subsongs 42-47 use 22000hz. They are tiny and silent, and maybe use the "play silence if invalid rate" trick, or are unused. But subsongs failing isn't nice, so you should add 22000 to the list (with explanation for bonus points). AFAIK that's the only exception, other files seem 22050/44100/48000.

**Comment by boringhexi** [comment]
Yes, those 6 subsongs are unused (player 3/4 sound effects in a stage that only has player 1/2). I've updated https://github.com/losnoco/vgmstream/pull/607/ to check for a simple range [11025-48000] and added details in comments.

**Comment by bnnm** [comment]
All good :)
