### ISSUE TITLE
Does VGMStream support the MDX/PDX (Sharp X86000) format?

### ISSUE THREAD

**Issue by Tenome** [losnoco/vgmstream#608]
It's an old but popular FM synth format. It has plugins and converters/players available already, so it'd be nice to see it added to VGMStream if possible.

https://en.wikipedia.org/wiki/X68000%27s_MDX
https://github.com/vampirefrog/mdxtools/blob/master/README.md
http://gorry.haun.org/mx/index_e.html
http://battleofthebits.org/lyceum/View/MDX+%28MXDRV+MML+for+Sharp+X68000%29/#MDX%20Players

**Comment by NicknineTheEagle** [comment]
vgmstream only supports streamed sound formats. It does not cover sequenced music.

**Comment by Tenome** [comment]
Ahh, my mistake. Now I know.
