### ISSUE TITLE
[Request] Support N64 AIFC files

### ISSUE THREAD

**Issue by derselbst** [losnoco/vgmstream#611]
It would be a nice feature, if vgmstream were able to read AIFC files, as shipped with the N64 SDK. Particularly, it should be able to decode the files and read its loop information.

The file structure is documented in the N64 SDK, e.g. here:
http://n64devkit.square7.ch/pro-man/pro19/19-02.htm

I'm not sure how well known the compression algorithm VADPCM is. But I would assume it doesn't differ too much from other ADPCM codings.

Also, I'm attaching a few demo files below.

[aifc_sounds.zip](https://github.com/losnoco/vgmstream/files/4535276/aifc_sounds.zip)
[Aifc.zip](https://github.com/losnoco/vgmstream/files/4535279/Aifc.zip)
[Aifc16.zip](https://github.com/losnoco/vgmstream/files/4535280/Aifc16.zip)

**Comment by bnnm** [comment]
Added. The codec is related but more complex than GC ADPCM btw.

**Comment by derselbst** [comment]
Amazing! Thank you very much!
