### ISSUE TITLE
[directly from zenhax] Rebellion Developments Asura Engine: *.WAV (Wii)

### ISSUE THREAD

**Issue by AnonBaiter** [losnoco/vgmstream#614]
just letting vgmstream devs know.
[https://zenhax.com/viewtopic.php?f=6&t=13507](https://zenhax.com/viewtopic.php?f=6&t=13507)

**Comment by kode54** [comment]
Files with common extensions must be renamed so the player's built-in support for those extensions doesn't take priority. Or you can move VGMStream to the top of the priority list, but then all common extension supported files will be handled, and that includes .ogg, and VGMStream doesn't display or edit tags.

**Comment by AnonBaiter** [comment]
so the sample files do work after all? if .wav is renamed to .lwav that is.
that aside someone asked to have a look at these files not me.

**Comment by bnnm** [comment]
This is not a repository of xentax/zenhax issues. Anybody is welcome to write about vgmstream issues, with actual sentences, not "go to this link and figure out".
