### ISSUE TITLE
.ASF (FIFA) files are not played in Winamp

### ISSUE THREAD

**Issue by vergol** [losnoco/vgmstream#615]
Files are working fine in foobar, but not in Winamp
https://mega.nz/file/mg9wQIAY#ENpFLBj6-H8LrCmPVpd5oIZK2iM-q4sPRO5UY0H2IC8

**Comment by NicknineTheEagle** [comment]
Have you tried changing extension to LASF? The player is likely hijacking the extension, this happens with common extensions.

**Comment by vergol** [comment]
Yes, renaming solves the problem.
