### ISSUE TITLE
FIFA Manager 07 .HDR/.DAT

### ISSUE THREAD

**Issue by vergol** [losnoco/vgmstream#616]
Files can be opened, but the sound is corrupted.
https://mega.nz/file/Ls80XYbC#TqPosgucqrVKkRF-kuqGZND-Lbunu4X_RhlbF5bjZE8

**Comment by NicknineTheEagle** [comment]
I think I got the issue pinned down, I just need to do a bit more investigation before pushing the fix.

**Comment by NicknineTheEagle** [comment]
Fixed here: https://github.com/losnoco/vgmstream/pull/617
