### ISSUE TITLE
Subsongs not supported when using Winamp plugin in XMPlay

### ISSUE THREAD

**Issue by jack980517** [losnoco/vgmstream#619]
If I uncheck "Disable subsongs", XMPlay can no longer play that file. If I check it, only the first subsong is played, which isn't what `test.xwb #1~3` seems to suggest.

I tried again in Winamp and found that the subsongs are displayed as individual entries in the playlist there. XMPlay has native subsong support (because tracker formats like mo3 can contain subsongs), so I think that should be used instead. (If that can't be done in the Winamp plugin, maybe update the XMPlay plugin?)

**Comment by kode54** [comment]
Subsongs in Winamp is already a gross hack: It has to use Winamp API to shove playlist entries into the playlist, and remove the initial track.

XMPlay uses something else to do subsongs: It expects the total time duration of a given song to be all of the subsongs smashed end to end, and it expects seeking across a track boundary to switch subsongs. This requires a native XMPlay plugin.

**Comment by bnnm** [comment]
XMPlay w/ Winamp plugin can't 'unpack' subsongs. XMPlay doesn't support Winamp's necessary playlist manipulation functions, and IIRC weren't going to be added.

Native XMPlay plugin I don't think can support vgmstream's subsongs either. Like kode says, XMplay subsongs are just time "subsections" of a single song (with same channels/sample rate/etc), and seems to be made with cues and trackers in mind so it isn't very flexible.

vgmstream subsongs however can be any mix of channels/rates/etc (and I don't think XMPlay can change those between "subsections"), and some banks have thousands of subsongs, so the resulting single-song-with-sections would be not very usable. I tried various ideas but couldn't do anything that seemed useful enough.

You could use [TXTP](https://github.com/losnoco/vgmstream/blob/master/doc/TXTP.md) instead, for example make an empty text file `test.xwb#3.txtp` and open that.

(or maybe ask the XMPlay author to improve the subsong API for vgmstream)

**Comment by jack980517** [comment]
Thanks for the replies. This was much more complicated than I first thought... I learned about XMPlay because of mo3 audio files in some games, and forgot to consider that tracker files are different from wave files. I'll try asking in the XMPlay forum then. After all, native subsong support is appealing, and XMPlay overall seems to be a player meant for game music, so I'd prefer that over Winamp.

**Comment by kode54** [comment]
foobar2000 and Winamp already support MO3 format files, using their libOpenMPT plugins. foobar2000 also using foo_dumb, but that's somewhat deprecated now, and I can't recommend it anyway, its mixer is way slower than libOpenMPT.

**Comment by sagamusix** [comment]
> and it expects seeking across a track boundary to switch subsongs

That's not true. Look at [libopenmpt's XMPlay plugin](https://github.com/OpenMPT/openmpt/blob/master/libopenmpt/xmp-openmpt.cpp) if you want to see how subsongs are done properly, in particular function openmpt_SetPosition, case `if ( pos & XMPIN_POS_SUBSONG ) {`

**Comment by kode54** [comment]
Yes, and they have to be the same format.

**Comment by bnnm** [comment]
Closing since there is not much to do. Feel free to reopen or post another issue if the XMPlay authors improve the API somehow.
