### ISSUE TITLE
(Problem/Question) .vxn file from Asphalt Injection (PS Vita) fails to play

### ISSUE THREAD

**Issue by Mtik333** [losnoco/vgmstream#620]
Hello.

I tried to play the attached file (that was found in Asphalt Injection PSVita files), but unfortunately I'm getting "file corrupted or unsupported" message in foobar2000 with VGMStream plugin installed. I tried newest release available: r1050-2946-g1e583645

I decided to also try "test.exe" (found in the r1050-2946-g1e583645 release) by using command:
`test.exe -o m_win.wav m_win.vxn`
However, this simply prints "failed opening m_win.vxn"

[AsphaltInjection_VXN.zip](https://github.com/losnoco/vgmstream/files/4605504/AsphaltInjection_VXN.zip)

I see that VXN.C file is in repository (though support for this format is not pointed on README.md), so it seems that audio file has something even more special than headers mentioned in the code (though it contains VoxN, Afmt and Segm chunks).

I'm kindly asking for help - if not with solving this little problem, then maybe some hints with debugging it and providing more developer-helpful info, where it fails to work (as I don't think I'm capable or allowed to fix it here)

**Comment by bnnm** [comment]
Working now:

https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts

**Comment by Mtik333** [comment]
Thanks a lot, it works after reinstalling plugin in foobar, I haven't tested test.zip but I think it will also stream it now.
