### ISSUE TITLE
[Request] Koei Tecmo GC ADPCM (Switch)

### ISSUE THREAD

**Issue by DeathChaos25** [losnoco/vgmstream#623]
Koei Tecmo Switch games use GC ADPCM (such as Fire Emblem: Three Houses, Persona 5: Scramble, Marvel Ultimate Alliance 3, and so on), and while it is possible to make a txth with the needed information to play the files back, the files may contain padding (and are very pointer based) which means sometimes a lot of different .txth files are needed even from audio coming from the same container, as it involves pointer maths, so I am making a feature request for this format with the .ktgcadpcm extension to read these files.

Attached below are sample files (with working .txth) from Fire Emblem: Three Houses (base game), Three Houses DLC, and 2 different Persona 5 Scramble samples, ALL with a different .txth, as well as a 010 Editor Template we have made that can be used to get the relevant info I used to make all the sample .txth files included (just use the template on the included .vgmstream files), this means no research is needed into the format, just an implementation of the 010 Editor template.
[Three Houses - Academy Ferdinand (base game).zip](https://github.com/losnoco/vgmstream/files/4625083/Three.Houses.-.Academy.Ferdinand.base.game.zip)

[Three Houses - Academy Balthus (DLC).zip](https://github.com/losnoco/vgmstream/files/4625104/Three.Houses.-.Academy.Balthus.DLC.zip)

[P5S - Morgana.zip](https://github.com/losnoco/vgmstream/files/4625105/P5S.-.Morgana.zip)

[P5S - ActBossDemi SFX.zip](https://github.com/losnoco/vgmstream/files/4625116/P5S.-.ActBossDemi.SFX.zip)

[KTGCADPCM 010 Editor Template.zip](https://github.com/losnoco/vgmstream/files/4625124/KTGCADPCM.010.Editor.Template.zip)

**Comment by bnnm** [comment]
You can actually use pointer tables with TXTH, kinda unwieldy though. This .txth works for all: [vgmstream.txth.zip](https://github.com/losnoco/vgmstream/files/4638159/vgmstream.txth.zip)

Generally, mini-subfiles from sfx sound banks that don't exist externally aren't added, unless there is some good reason (made up extensions are no good, plus I feel TXTH gives enough tools to play around in those cases).

Instead, I'd rather add the original container, since that's what most people would try to open with vgmstream, without having to extract subfiles first. I take it's .ktsl2stbin w/ KTSR, so you could upload samples for that instead. KTSR with other codecs is also used in other platforms (I have samples for those).

**Comment by DeathChaos25** [comment]
I don't mind uploading samples for the KTSR files instead, although those can get weird since they contain more than just the sound (they also tend to contain data for external audio files?).

2 Samples from Three Houses (Base Game + DLC), and a random assortment of samples from P5 Scramble that I have no idea where they belong due to the game being JP only at the moment. Usually, KTSR files are found with the .ktsl2asbin file extension (where filenames exist), there's also weird cases like P5S where the KTSR file is in a .srsa """wrapper""" (literally 0x10 bytes of useless data because KTSR itself already has filesize data).

[Three Houses - Byleth (Female).zip](https://github.com/losnoco/vgmstream/files/4638279/Three.Houses.-.Byleth.Female.zip)
[Three Houses - Hapi (DLC).zip](https://github.com/losnoco/vgmstream/files/4638281/Three.Houses.-.Hapi.DLC.zip)
[P5S KTSR Samples.zip](https://github.com/losnoco/vgmstream/files/4638288/P5S.KTSR.Samples.zip)

**Comment by bnnm** [comment]
Works now. https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts

I didn't add the .srsa wrapper since it looks like some generic thing not really related to the KTSR.

Probably needs support for .ktsl2asbin+.ktsl2stbin w/ KTSS, post if you find some.

**Comment by Mysticus92** [comment]
For Atelier Ryza, the voices files still doesn't work for some reason.
Do you plan to fix it?

**Comment by bnnm** [comment]
I don't have those files so you'd need to post samples.

**Comment by Mysticus92** [comment]
Here.
https://drive.google.com/file/d/16wAEnoqN7BkKZvBQVEm7tS4wn1IFMD_k

**Comment by bnnm** [comment]
Those work now.
