### ISSUE TITLE
opus format dpcm support request.

### ISSUE THREAD

**Issue by keesoudwater34** [losnoco/vgmstream#626]
i wanted to ask if there is any way that the support for the opus formats can be extended to the dpcm format. its as far as i know a subformat of the opus standard but it wont read it. so id like to know if there is a way it can be supported. included 2 samples 
[bf01120150_se01.zip](https://github.com/losnoco/vgmstream/files/4670225/bf01120150_se01.zip)

[bf01010100_se01.zip](https://github.com/losnoco/vgmstream/files/4670216/bf01010100_se01.zip)

**Comment by bnnm** [comment]
Should work now.

https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts
