### ISSUE TITLE
Some Unity FSBs not playing correctly

### ISSUE THREAD

**Issue by Mohamed00** [losnoco/vgmstream#640]
Hi, I've noticed an issue where some short FSBs extracted from Unity games aren't playing correctly, though I wonder if it's just an FSB with a key that hasn't been found. Example: https://drive.google.com/uc?id=1Qd9x80BP1dsfPJn7N5cFOuZp1djLNbmD

**Comment by bnnm** [comment]
The file looks incorrectly extracted. Final size should be 0xC20 but is 0xE60 (remove the excess data and it plays normally), you may need to change your extractor.

**Comment by Mohamed00** [comment]
I used the Unity support built into Game Extractor at the time, since the unity extractors I found seemed to not be able to extract the original FSBs and keep the names. Any suggestions for alternatives to it?

**Comment by bnnm** [comment]
Maybe try Unity Asset Studio, though you need to set an option to extract original .fsb (converts to .wav by default) and it's prone to crash if given too many files at once.

https://github.com/Perfare/AssetStudio/releases

**Comment by Mohamed00** [comment]
That worked, thanks.
