### ISSUE TITLE
BNSF IS14sfmt noise

### ISSUE THREAD

**Issue by MarieRose1301** [losnoco/vgmstream#644]
Hello, I've been trying to dump The iDOLM@STER: One For All vocal tracks, and have encountered an issue where vgmstream opens the file, recognizes the track name and length but the playback is just noise, what could be causing this? The other nus3bank files dumped from the memory load fine though, as do the similar imas2 vocal tracks.

[song2_edn_tak.nus3bank.zip](https://github.com/losnoco/vgmstream/files/4738012/song2_edn_tak.nus3bank.zip)

**Comment by bnnm** [comment]
The audio is encrypted. If you post an emu memory dump I can probably extract the key and fix it.

**Comment by MarieRose1301** [comment]
@bnnm https://www.dropbox.com/s/ozdhnvnh63tassy/rpcs3.DMP?dl=0

**Comment by bnnm** [comment]
Added: https://ci.appveyor.com/project/kode54/vgmstream/branch/master/artifacts
