### ISSUE TITLE
foobar2K vcxproj needs to be upgraded

### ISSUE THREAD

**Issue by NWPlayer123** [losnoco/vgmstream#646]
it still requires v141_xp which is super deprecated (both 2017 and the XP support)
![image](https://user-images.githubusercontent.com/3280345/83965106-6dc94f80-a86e-11ea-897b-93222a491631.png)

**Comment by bnnm** [comment]
I don't think the project 'requires' that. You can probably change it locally to your thing without issue.

As for the default, some users still use XP IIRC. Surely you can see the irony of "needing to upgrade" an old lib, using an old programming language, targeting old music players, to play old video game music.

**Comment by NWPlayer123** [comment]
I'm just saying don't be surprised when they stop offering it and you can no longer compile for that version, it's mainly about accessibility
I also find people using XP abhorrent, an OS that hit end-of-life and will have major security flaws continue to be discovered

**Comment by kode54** [comment]
FYI foobar2000 1.6 alpha dropped support for XP.

**Comment by bnnm** [comment]
When changing defaults I try to put some weight behind that decision, like it makes maintenance easier, or its needed to compile recent stuff, or actually nobody needs that. But if some kid comes asking "I updated vgmstream but it stopped working, I'm using XP", the reason I have right now is "sorry, I find you abhorrent so I switched XP support off".

TBH I don't even know what that value does, nor I use that default to compile. I take it would just disable XP support, or maybe nothing would even change?

**Comment by NWPlayer123** [comment]
The reasons are
1) the default toolset is deprecated and will stop being hosted in the future
2) foobar2000's latest release (1.6 alpha) doesn't support XP anyways so that will break compatibility even if the toolset is still around
3) Visual Studio can't even run on Windows XP so you need a newer OS to compile the plugin *anyways*

the choices for XP users are either: update their OS to something newer than 2001, or use a version of foobar2000 older than 1.6 and ask someone with a newer OS to compile the latest vgmstream and fb2k plugin and send it to them

Visual Studio 2013 doesn't even support XP, much less 2019
https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2013-sysrequirements-vs
![image](https://user-images.githubusercontent.com/3280345/84087499-75d8da80-a9a7-11ea-91e6-a7c0a8101e8f.png)

**Comment by bnnm** [comment]
Not really getting your points. People using XP aren't going to use cutting-edge foobars, nor have VS. Compiling with support for older, unsupported OSes is a completely normal thing (like, in Win10 for Win7). I change the default toolset in my system, so in the source I take it just means if we serve appveyor builds for XP or not.

Anyway, I think @kode54 should decide, since foobar is more his thing. If somebody complains I'll point them to this issue.

**Comment by kode54** [comment]
This project can continue building for XP, I guess, as long as Visual Studio keeps supporting that. But I won't be verifying it actually works there.

**Comment by kode54** [comment]
Incidentally, I'll just let the SDK force this issue the very day that it starts defaulting to v142. Which I doubt will happen, judging by Peter's stance on Visual Studio 2019.

(The last time he tested 2019, it outright crashed just attempting to load his entire solution to debug something. So for now, the newest he'll touch is 2017.)
