### ISSUE TITLE
[Request] Support for .brsar?

### ISSUE THREAD

**Issue by blurengo** [losnoco/vgmstream#652]
Found these music files looking around trying to grab original files for the music (Wii).
I want to listen to them but they are not supported in vgmstream.
![explorer_2020-06-16_12-26-30](https://user-images.githubusercontent.com/35280197/84813125-af739c00-afcc-11ea-8256-edf1a088eac4.png)

**Comment by MDHEXT** [comment]
Not possible. The brsar container format has steams in it that can be ripped by extracting it. The brsar format as a whole is not in itself an audio file and thus cannot be opened. The brsar you have does not contain any streamed music files, but contains music sequences and their associated banks. Music sequences cannot be ripped currently but can be converted to midi. VGMStream does not support sequenced music formats, so those formats will not be added to VGMStream.
