### ISSUE TITLE
Using this to extract xwb/xsb?

### ISSUE THREAD

**Issue by IngwiePhoenix** [losnoco/vgmstream#656]
Persona 4 Golden released for PC and it was great to play through it for the second - and soon third - time. However, I have been thinking about mods immediately after it's release; and wouldn't you know, I wasn't alone.

One of the big features that is already employed is the ability to replace sounds. However, right now it's a little...tricky, to say the least. There is no really good way to extract XWB/SWB couples into a plain folder to just listen to them and figure out which is what. Using vgmstreamer with fb2k is a great solution - but, quite frankly, its clunky.

Would it be possible to use this tool to extract the entire couple into a folder using their in-bundle names? For instance: Using the `unxwb` tool only yields hexadecimal filenames (i.e. `00000000.wav`). But the mod loader uses eitheir their load index OR their in-bundle name, which is much more readable and handy: `BGM031` corresponds to one of the dungeon themes. If one was to replace it, they'd create a `BGM031.raw` (PCM encoded) and associated `BGM031.raw.txth` file that would dynamically be loaded in. This is a nice, and mostly human readable way to work with replacing sounds.

However, as nice as it is to just load up the corresponding couple in fb2k, it'd be nice to extract them to individual files as well. Would this be possible? I saw the CLI tool, but it didn't seem to support just outright extracting WAVs and WMAs off the bundle...

**Comment by NicknineTheEagle** [comment]
vgmstream is a sound decoder not a file extractor.

**Comment by IngwiePhoenix** [comment]
I know that it isn't - but thus far, its the only way to get to contents within XWB files and `unxwb` isn't working quite well. So clearly, vgastream han properly read XWB archives to play the sounds from within. I had just hoped that it'd be possible to use that fact to extract all the sounds from that archive.

**Comment by NicknineTheEagle** [comment]
The parser is here:
https://github.com/losnoco/vgmstream/blob/master/src/meta/xwb.c
One could probably use the info from here to write XWB extractor tool. But like I said, extraction is not a part of vgmstream's functionality.

**Comment by bnnm** [comment]
You could use this tool: https://github.com/bnnm/vgmstream-builds/raw/master/bin/xwb_split_114.7z.

However I recommend you use [TXTP](https://github.com/losnoco/vgmstream/blob/master/doc/TXTP.md) instead to play select songs.

In short, if you have `bgm.xwb` you can make an empty file named `bgm.xwb#31.txtp` and open that to play subsong 31.
