### ISSUE TITLE
Reign Of Fire .BSF banks

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [losnoco/vgmstream#664]
These contain multiple files, with the stereo channels of each track split into two separate chunks(usually marked with a _L and _R suffix)
Some info and a few samples are on the HCS discord here: [https://discordapp.com/channels/502387933341417482/502388312850300928/730923584226328658](url)
Sound effects and VO use the same bank format, so those should work as well.
The game is multi-platform, so i'll update this post if i see any differences with the PS2 version compared to Gamecube but i doubt there will be any.

**Comment by bnnm** [comment]
Added.
