### ISSUE TITLE
Output files with stream names

### ISSUE THREAD

**Issue by Toshiba1127** [losnoco/vgmstream#670]
After extracting subsongs, I need to see the stream names on output console and rename them maunally but it's a quite a pain if there are a lot of files

My suggestion is to extract and output files with stream name so I can just do command like:
`test.exe -s 3 -od (output directory) (target file)`

`for /L %A in (0,1,99) do test.exe -s %A -od (output directory) (target file)`

outputs the following as an example
```
select_AVEX_01_STROBE.wav
select_AVEX_02_INNER_FIGHTER.wav
select_AVEX_03_CURIOUS_D_MIX.wav
```

but keep the `-o` for output file with manual naming

**Comment by bnnm** [comment]
I think easiest to add but more complete would be some kind of wildcard/substitution name for `-o`:

` test.exe -s 3 -o ":s.wav"` could use subsong: `3.wav`
` test.exe -s 3 -o ":n.wav"` could use stream name: `select_AVEX_03_CURIOUS_D_MIX.wav` (or filename if stream name isn't set)
` test.exe -s 3 -o ":n__:04s.wav"` would create `select_AVEX_03_CURIOUS_D_MIX__0003.wav`

Does that work for you?

**Comment by Toshiba1127** [comment]
Oh yeah that would work. That would be perfect!

**Comment by bnnm** [comment]
Added, using `?` instead of `:` to avoid path conflicts, also `?f` = filename.

Info: https://github.com/losnoco/vgmstream/blob/master/README.md#testexevgmstream-cli
(builds [here](https://ci.appveyor.com/project/kode54/vgmstream)).
