### ISSUE TITLE
Sega Rally 3 .sfx and .stm sound banks

### ISSUE THREAD

**Issue by AndnixSH** [losnoco/vgmstream#673]
Would love to have support for .sfx Sound Banks and .stm Stream Data File. They seems to be custom made

https://drive.google.com/file/d/1-kmh13ohZs1KDS8g5Uf1rUi3wWdHADOS/view

Executeable file to disassemble if you want

https://drive.google.com/file/d/1soQ1ED-xlSJYSjxDG646pf7cfdq4YxzU/view

**Comment by bnnm** [comment]
This format seems a bit too generic archive to be properly added. Instead, download the attached file, unzip near the stm/sfx and open the .txth files.

Those tell vgmstream how to play the archives, should be an ok substitute I think. If more games do use this format as a sound archive it could be added later.

[sega-rally-3-pc-txth.zip](https://github.com/losnoco/vgmstream/files/5011071/sega-rally-3-pc-txth.zip)

**Comment by AndnixSH** [comment]
Oh thanks. It worked on foobar2000
