### ISSUE TITLE
Paper Mario: The Origami King opus won't loop

### ISSUE THREAD

**Issue by lin010151** [losnoco/vgmstream#683]
I ripped some opus from Paper Mario, but they won't loop while playing. I forked the project and tried to add some code (I'm not good at coding) but I don't know how to find necessary things like loop_start or loop_end. What should I do?

Also, what are the differences between ogg_opus.c, opus.c and opus_ppp.c? As they all deal with opus and they all have nintendo switch games.

**Comment by bxaimc** [comment]
The opus from Origami King don’t contain loop points. They’re stored externally within the bfsar.

**Comment by lin010151** [comment]
Is that mean I should also rip the bfsar and then put it into the play list with opus?

**Comment by bxaimc** [comment]
Unfortunately, ripping the bfsar won’t work. That would only extract the sfx inside of it. The loop points are stored in a different block and I don’t think there are tools than can parse it and print out the respective loop point sets without making your own, but I could be wrong as I haven’t checked.
