### ISSUE TITLE
Vgmstream123/Audacious plugin unable to play wem files 

### ISSUE THREAD

**Issue by Sci3ntia** [losnoco/vgmstream#689]
recently i've moved from windows to ubuntu, and had to stop using fb2k and moved to audacious, however vgmstream123 and libvgmstream seem unable to play my wem files (xenoblade chronicles definitive NX), while running foobar2k under wine with vgmstream plays them fine, am I missing something or is there an issue?

**Comment by kode54** [comment]
Did you build it yourself? Did you also enable the optional dependencies? Maybe try the CI builds for Ubuntu from here:

https://ci.appveyor.com/project/kode54/vgmstream

**Comment by bnnm** [comment]
Your wem need FFmpeg codec enabled. If you use cmake to build Audacious (or the Ubuntu CI builds linked above) it should work, but when building with autotools it isn't enabled at the moment.

First try cmake/CI builds, and if that fails for autotools you could try `sudo apt-get install libavformat-dev libavcodec-dev libavutil-dev libswresample-dev` and uncommenting lines 39/40/41 here then building, but I couldn't get it to work.

build info here: https://github.com/losnoco/vgmstream/blob/master/doc/BUILD.md#audacious-plugin

**Comment by Sci3ntia** [comment]
Thanks for the quick response, I'll try this, thanks

**Comment by Sci3ntia** [comment]
Thanks so much, works perfectly now
