### ISSUE TITLE
some .lwav foobar2000 playback and format conversion issues

### ISSUE THREAD

**Issue by yurmad** [losnoco/vgmstream#693]
Hi, I am having a bit of a problem playing some .lwav(renamed from .wav) files with foobar2000. The audio files were extracted from the same file from a recent Rainbow Six Siege Test Server build. Some play for a split second and just suddenly turn into complete silence, some are silent right from the start, some play just fine. I used a hex editor to check just to be sure and their data chunks all look fine to me.
some examples that don't work:
https://mega.nz/folder/bVFlmaTJ#ZvUp0lm5pUENbeB68e1AqQ
some examples that work:
https://mega.nz/folder/mVN1DS5R#_R1ietez2uymRDKgdwQI6A
Also, when I convert the audio files to another format(like standard .wav for example), and use the hex editor to check the output files, the silent part of the output consists of pure zeros.

**Comment by yurmad** [comment]
So I've fixed all my previously broken files except one that doesn't play correctly. I'm not sure if this one is still a extraction problem or a playback problem. It somehow starts having a electric noise in the background and it becomes stronger and stronger for 2-3 seconds until it turns into a very loud clipping noise and then plays normally right after that just before it ends. It doesn't sound like my previous issue so I'm confused.
Here's the file: https://mega.nz/folder/7B1j3BbL#LpVmJQu5AML4Z-imrhB2bA

**Comment by bnnm** [comment]
It gives decode errors after a point, so it's still non-audio data in the middle, or incorrectly extracted from .bnk (can't really tell you which).

**Comment by yurmad** [comment]
So is there any way I can locate the address where the errors begin to happen?

**Comment by bnnm** [comment]
Generally you can't tell if random parts are wrong since it may simply generate incorrect audio but keep decoding.

On a second inspection decoding errors are only for missing data in the last bytes (0x88B0C), due to manual cutting I guess. The waveform looks normal without clips:

![imagen](https://user-images.githubusercontent.com/22844311/91212564-b1668380-e710-11ea-9118-a209d20bbedd.png)

**Comment by yurmad** [comment]
It could cause some crashes last time, so I'm thinking maybe now that it is fixed it can try to return the address where the problem happened as well. I basically fixed the previous problem by deleting 16 extra bytes they added in the middle of those files, and adding those zeros you saw in the end for convenience. But I was using current live server build old season audio extracted from .pck files to compare with test server build old season audio extracted from these new .forge files to find out about this thing they did, but this new issue doesn't appear to happen to any other music audio in the files at all and it's also newly added audio so it seems like figuring out the address is the only way to fixing this.

**Comment by yurmad** [comment]
Well, looks like there is no way to fix it for now. I'll close the issue.
