### ISSUE TITLE
Floating Point PCM LWAV playback fails

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [losnoco/vgmstream#696]
The tool "Legion" exports Titanfall 2 and Apex Legends audio as floating-point PCM
AL music in particular would be good to have working in vgmstream for it's down-mixing since all music is 8 channels.

However renaming the WAV files exported by Legion to LWAV means they don't play at all in Foobar.
[https://cdn.discordapp.com/attachments/419711036837330956/747590985982148746/R5_Suite10_Adventure_Victory_1648_8chMix.wav](url)
Linked is a short track from AL to test with.

**Comment by NicknineTheEagle** [comment]
vgmstream only supports audio codecs actually used by games and, IIRC, Titanfall 2 does not store its audio as float PCM, this is rather the format Legion tool converts the audio to.

**Comment by bnnm** [comment]
Titanfall 2 and Apex Legends actually use "binka" (similar to bink video but for audio) which IIRC the tool converts to PCM float using game's DLLs.

**Comment by richardpl** [comment]
I have binka demuxer, if you wanna peek at it.
