### ISSUE TITLE
Atelier Lulua/Ryza (Steam) .ktsl2asbin files problem

### ISSUE THREAD

**Issue by Mysticus92** [losnoco/vgmstream#703]
For Atelier Lulua (Steam), some .ktsl2asbin files like "voice" doesn't seem to work at all.
Also some files like "battleskill" doesn't load subfiles.
https://drive.google.com/file/d/1Xv-7vJEnCX_tZUCih8zS6FLZBse__Eq9
And as for Atelier Ryza (Steam), all .ktsl2asbin like "SE_field" doesn't load any subfile.
https://drive.google.com/file/d/1BqhcdndVDN9NEZyF7-De9EHyI7_mVMLy
Do you plan to fix them and adding subfiles?

**Comment by Mysticus92** [comment]
Thanks for fixing some Atelier Lulua and Ryza sound files. But the issue isn't over yet.
For Lulua, the .ktsl2asbin files like "battleskill" and "voices" don't have any subsong names after uploaded in foobar2000.
https://drive.google.com/file/d/1rsJJu4-8v8OBVNCnOg1Fp2Hs2kUaQybr
And for Ryza, all .ktsl2asbin files like "SE_field" still don't have subsongs at all after uploaded in foobar2000.
https://drive.google.com/file/d/1XnjbumnCiQRDFKEtA64efTSje2RdeKH0
Please, add subsongs from them.

**Comment by Mysticus92** [comment]
Thanks for fixing these .ktsl2asbin files. But the issue isin't over yet.
"battleskill" and "voice" files from Lulua still don't have hidden file names like the rest.
![Cattura](https://user-images.githubusercontent.com/67751769/93012978-cd897200-f5a4-11ea-978c-f443d3722749.PNG)
![Cattura2](https://user-images.githubusercontent.com/67751769/93013004-fc9fe380-f5a4-11ea-96c1-e38a2b49ff46.PNG)

And as for Ryza, all .ktsl2asbin files like "SE_battle" have no hidden file names at all.
![Cattura](https://user-images.githubusercontent.com/67751769/93013049-4688c980-f5a5-11ea-99f7-0d6ff1d9dd57.PNG)

Any plans updating them one more time?

**Comment by bnnm** [comment]
Those files don't have any names inside (they are optional), probably skipped when files with many subsongs.

**Comment by Mysticus92** [comment]
Please. Only for once include names inside these files that I mentioned.

**Comment by kode54** [comment]
He's not saying they're skipped by VGMStream. He's saying they're skipped by the developer when authoring files with lots of subsongs, and therefore don't exist for us to index.

**Comment by Mysticus92** [comment]
Then I guess there's no way to add hidden names in them right?

**Comment by bnnm** [comment]
It is impossible. battleskill/voice/SE_battle don't have hidden names.
