### ISSUE TITLE
Kandagawa Jet Girl (Steam) .acb/.awb error

### ISSUE THREAD

**Issue by Mysticus92** [losnoco/vgmstream#706]
All of these files sounds so glitched.
Do you have time for fixing?
[Kandagawa Jet Girls rip.zip](https://github.com/losnoco/vgmstream/files/5220628/Kandagawa.Jet.Girls.rip.zip)

**Comment by bnnm** [comment]
Files are encrypted. Post the executable and maybe the key can be extracted.

If the game uses Unity, find and post all files called level0/level1/etc, globalgamemanagers, global-metadata.dat, unity default resources, 00000000000000000000000000000000 and similar ones.

**Comment by Mysticus92** [comment]
Sure!
I can post all the game data tomorrow though.

Il Mar 15 Set 2020, 22:40 bnnm <notifications@github.com> ha scritto:

**Comment by Mysticus92** [comment]
Sure!
And yes, it uses Unity engine.
It's gonna take a while though.

**Comment by Mysticus92** [comment]
Here you go. Sorry if it's too big to download for you.
https://drive.google.com/file/d/1g7Q-Aa012PejPw-Xyfh3YSjOgV5jUDQF

**Comment by bnnm** [comment]
Works now, same with Re:Zero.
