### ISSUE TITLE
Trials of Mana music not opening

### ISSUE THREAD

**Issue by Colmines92** [losnoco/vgmstream#708]
Trials of Mana music not opening.
The bgm files (right now i down't remember what extension it has) have the same extension that those from Secret of Mana Remake (those plays ok). I opened both with an hex editor and there are only a few bites different on header, if I cut the header and let it as HCA it now opens fine.

If needed I can supply sample file tomorrow.

**Comment by bnnm** [comment]
Post several (not one) files to test.

**Comment by Colmines92** [comment]
Here are the samples.
3 of each Trials of Mana (not working) & Secret of Mana (working).
The file extension is .win.sab and inside they contain an HCA file that works perfectly in both cases.

[samples.zip](https://github.com/losnoco/vgmstream/files/5250020/samples.zip)

**Comment by bnnm** [comment]
They are incorrectly extracted and contain Unreal Engine garbage towards the end (value 0xC1832A9E and beyond). Remove that manually or try other extractors, .sab size must match value at 0x0C.

**Comment by Colmines92** [comment]
Oh, you are absolutely right!
I removed the remaining bytes from it and it works perfectly.
Sorry for my mistake, it hadn't even crossed my mind that it was that.
