### ISSUE TITLE
Winamp crash with "access violation" error when playing files with subsongs

### ISSUE THREAD

**Issue by mbc07** [losnoco/vgmstream#711]
I normally use vgmstream plugin through XMPlay but it currently [doesn't support direct playback of subsongs](https://github.com/losnoco/vgmstream/issues/619), so for a particular rip I'm working on I decided to temporarily switch to Winamp, to be able to seek through the subsongs more easily. Then I discovered subsong support in Winamp is very very prone to crash (always with an "access violation" error).

I don't know if that's always been the case but I tried vgmstream r1050-3258-g0b7c3ce6 (Sep 12 2020) with both Winamp 5.8 (build 3660) and also Winamp 5.66 (build 3516) and it always goes like this:

1. File with subsongs get added to the playlist with a "#X~X" at the end
2. Upon playing that file, it gets replaced with a "#1" at the end and entries for each subsong get added into the playlist automatically
3. Winamp starts playing the first subsong but after ~2 seconds it suddenly closes and their crash report tool opens

The only way I found to avoid the crash is to do this every time you launch Winamp (and before trying to play a file with subsongs, even if they already exists on the playlist):

1. Add a file to the playlist that doesn't have any subsong or disable subsong support in vgmstream settings and add a file with subsongs (it must be a file format played by vgmstream, e.g. if you add a MP3 file it'll be handled by other plugin thus it won't work)
2. Play that file, it will work normally (if it's a file with subsongs, only the first one will play)
3. That's it. Now you can reenable subsong support in vgmstream settings and add/play files with subsongs to the playlist  without causing Winamp to crash. This "fix" persists until you close Winamp.

I don't know if that's useful but [here is the crash report](https://github.com/losnoco/vgmstream/files/5249021/report_wa5.8.zip) that Winamp generates after triggering the bug. Maybe a memory leak somewhere is causing this?

**Comment by bnnm** [comment]
Winamp subsongs work for me using [latest release](https://github.com/losnoco/vgmstream/releases/tag/r1050-3264-g86fbfffd).

Post the file you are trying to open since that is what matters most. As for the dump repost with that exact release (to match symbol file). Maybe try disabling other plugins that could affect output, like dsp too.

**Comment by mbc07** [comment]
It's not that subsongs doesn't work, they **do** work, but I always have to do the workaround steps I mentioned before, otherwise Winamp will always crash with an "access violation" error when it starts playing a file with subsongs. 

The only external plugin installed on Winamp is vgmstream and all built-in DSP plugins are disabled. Tried switching between the built-in DirectSound, WASAPI and WaveOut output plugins but nothing changed, the crash still happens if I don't do the workaround steps.

As you requested, I updated to the latest GitHub release of vgmstream and tried several different files with subsongs (mostly Wwise BNK and Criware ACB, but some other formats too) and the crash is always reproducible. Here is a new crash report of [Winamp 5.8 build 3516 with the latest vgmstream release](https://github.com/losnoco/vgmstream/files/5250733/report_wa5.8_vgmstream-latest.zip), as well as [two different file samples with subsongs](https://github.com/losnoco/vgmstream/files/5250785/subsong_sample.zip) that you can use to trigger the crash (however any file with subsongs seems suitable)...

**Comment by bnnm** [comment]
By "subsongs work" I meant "they are playable and didn't crash the player for me".

Anyway, seems it only crashes when using Bento skin and not "classic", for some reason (maybe some other skins trigger this), test latest appveyor release.

**Comment by mbc07** [comment]
Just gave it a try, no crashes anymore! Fixed by #712
