### ISSUE TITLE
Who can help solve the problem of unpacking BIN file ?

### ISSUE THREAD

**Issue by iqeqsun** [losnoco/vgmstream#713]
Documents from Touhou Cannonball 東方キャノンボール

Follow these steps 

       VGMToolbox               HCA Decoder
acb ——————–> hca ———————–> wav

Using VGM to convert ACB and AWB is not HCA but BIN file，ACB → HCA → WAV cannot be converted , according to the discussion of online information and forum, guess the BIN file should be encrypted, ask for your help.

Download foo_input_vgmstream plugin then dropped all the AWB files into Foobar (with vgmstream) and they seem to play with no issues , but I'm curious what is the .bin file extracted from .acb ?

Here is a zip File of Touhou Cannonball
Touhou Cannonball - touhou CB
https://mega.nz/#!lBYQiSYA!8AIqHkh3XjPA75uvn63Ih8AlWKywvYuYeCxAVQjV7SE

Here is a .Bin File that extracted from ACB File
Touhou Cannonball - sdcache EncodeType-06.bin.zip
https://mega.nz/#!hAxkRSTL!EW5odbbTgF-uttgfiFPD0TV2F3LuMTg9n3J4Z92PifA

The problem is similar to the following post：

HCS Forum - Tokyo Ghoul: Re Invoke .ACB and .HCA sound issue
https://hcs64.com/mboard/forum.php?showthread=52151
Tokyo Ghoul: Re Invoke .ACB and .HCA sound issue by TheGoldenChild at 4:06 PM EDT on September 19, 2017

It seems like the files I have are encrypted and I don't know how to unencrypt them are where to start. Each time I try to play a sound there is nothing but static in Foobar2000.

Here is a .Bin File
https://www.mediafire.com/file/2b8j5wu79iqvhwb/emotion_2.EncodeType-06.bin

**Comment by bnnm** [comment]
Try renaming .bin to .hca

**Comment by Mysticus92** [comment]
Or better, instead of putting these files in VGMtoolbox, you should put them directly to foobar2000.
Simple.
