### ISSUE TITLE
MSM6295 is low sound quality

### ISSUE THREAD

**Issue by ymbon** [losnoco/vgmstream#726]
I think low sound quality in MSM6295 sound. 
Please confirm this issue. 

I listen arcade music. (Ex. CPS1 SF2) 
The drums sound like low sample rate. 

I checked the same vgz file in another application. 

I love vgmstream. 
Thank you for your work. 
(My English is not very good, but I'll try my best!)

**Comment by CyberBotX** [comment]
I think you've confused vgmstream with VGMPlay / in_vgm. They are not the same thing. You should direct this to https://github.com/vgmrips/vgmplay instead.

**Comment by ymbon** [comment]
Dear CyberBotX.

I'm sorry.
I confused other project.
(Plugin name is Game Emu Player.)

Thank you for your comment.
