### ISSUE TITLE
Some audio files from Roblox can't play

### ISSUE THREAD

**Issue by AndnixSH** [losnoco/vgmstream#727]
I have got some audio files from cached location of Roblox. Some of them can't open with vgmstream but it can open with Audacity.

Here are the files you can check difference between unsupported and supported files

[Unsupported files.zip](https://github.com/losnoco/vgmstream/files/5357219/Unsupported.files.zip)

[Supported files.zip](https://github.com/losnoco/vgmstream/files/5357222/Supported.files.zip)

**Comment by kode54** [comment]
They all appear to be simple files: A simple header containing the Amazon S3 URL that the file was sourced from, along with the HTTP response headers from the last time the file was fetched. Not sure about the format of the headers, but immediately following them appears to be a plain Ogg Vorbis stream, as indicated by the "OggS" header.
