### ISSUE TITLE
.aac Star Ocean 4 PC

### ISSUE THREAD

**Issue by alittlered** [losnoco/vgmstream#730]
[https://mega.nz/file/KbhjwKDR#gaE1tHaYU3y108hrIzvoR949cjE-TKatUWTJGZ3bdgE](url)

PC so4 unpacker:
[https://github.com/RikuKH3/so4pc_pack](url)

PS:
If someone is insterested in this, please tell me where the battle voice and battle se is.
I had tried get them in Xbox version, but didn't find it.

**Comment by bnnm** [comment]
Fixed: https://vgmstream-builds.losno.co/

You may need to rename to .laac depending on your config.

Battle voices I think are in later .aac as subsongs.
