### ISSUE TITLE
Mario Kart Live: Home Circuit wem file issues

### ISSUE THREAD

**Issue by MDHEXT** [losnoco/vgmstream#731]
Some opus-encoded files are playing at a lower sampling rate than they should be (all of which are Voice clips). I am also having some trouble with the course maker music. my syntax is correct, but the TXTP file refuses to play even though both the intro segment and main track play when they are not put into one file.
TXTP commands:

```wem\357934011.wem
wem\389010260.wem
wem\559177124.wem
wem\830755738.wem
wem\961509376.wem
group = 1L5
group = 1S1

wem\288971295.wem
wem\374867557.wem
wem\167232507.wem
wem\12044704.wem
wem\206910299.wem
wem\676385493.wem
group = 1L6
wem\288971295.wem
wem\374867557.wem
wem\167232507.wem
wem\12044704.wem
wem\206910299.wem
wem\724384367.wem
group = 2L6
group = 2S2

mode = segments
loop_start_segment = 2
commands = #@layer-b 2 1~14 #@volume 2.0917029071028517
```
I've attached a zip with all the wems used here. I have no idea why it doesn't work and I hope this isn't something I did.
[wem(s)](https://github.com/losnoco/vgmstream/files/5394988/wem.zip)

**Comment by bnnm** [comment]
Fixed voices. That txtp fails because you are trying to combine layers of different number of channels. Try something like this with a recent vgmstream:

```
wem\389010260.wem
wem\559177124.wem
wem\830755738.wem
wem\961509376.wem
group = -L4 #@layer-b

wem\288971295.wem
wem\374867557.wem
wem\167232507.wem
wem\12044704.wem
wem\206910299.wem
wem\676385493.wem
group = -L6 #@layer-b

wem\288971295.wem
wem\374867557.wem
wem\167232507.wem
wem\12044704.wem
wem\206910299.wem
wem\724384367.wem
group = -L6 #@layer-b
group = -S2

mode = segments
loop_start_segment = 2
commands = #@volume 2.0917029071028517
```
