### ISSUE TITLE
Unsupported .SGT files

### ISSUE THREAD

**Issue by Colmines92** [losnoco/vgmstream#735]
Don't know if you accept any audio file type.
Those are from Gothic2 PC:

https://www90.zippyshare.com/v/3yxb0cZf/file.html

I had to upload them to ZippyShare because they were bigger than 10Mb.

**Comment by Mohamed00** [comment]
I believe these might be slightly out of scope for vgmstream. These 
files are DirectMusic segments, which are more MIDI than streamed. The 
SGT files have associated style files, .sty, which contain pattern data, 
along with DLS banks that have the actual sounds the SGTs require. You 
can play these with a program such as Simple DirectMusic Player.

**Comment by bnnm** [comment]
They are sequenced so not suited for vgmstream.

Some info: http://www.vgmpf.com/Wiki/index.php?title=SGT
