### ISSUE TITLE
unsupported wwise bnk (Shadowrun 2007 - Windows version)

### ISSUE THREAD

**Issue by RetingencyPlan** [losnoco/vgmstream#737]
okay, first of all these bnk files have been tested with latest vgmstream update.
as it is right now, only vgmstream is willing to work with base.bnk and sr_vo_stream.bnk, respectively.
because they have dummy entries. :/
the rest of the bnk files don't play at all despite most of them containing a bunch of sounds stored in those files.
said sounds were encoded with an older IMA ADPCM codec which vgmstream has full support of.

here are the samples.
[unsupported_bnk_files[shadowrun_2007][microsoft_windows].7z](https://1drv.ms/u/s!Asofkpy7aqyKwivghXbo455Ks33R?e=dmSke8)

**Comment by bnnm** [comment]
Should work now.

**Comment by RetingencyPlan** [comment]
the whole thing actually worked now. thanks.
