### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by mrobaczyk** [losnoco/vgmstream#746]
Hey, first I want to say that the tool is awesome. I'm using it to convert wem to wav. But I have a little concern, namely that the files are big. Is there any way to compress them using your tool or can you recommend some other tool I could use?

Thanks for help

**Comment by NicknineTheEagle** [comment]
vgmstream is a decoder, it does not provide encoding/compression capabilities. If you goal is to transcode VGM files into a different compressed format, it's easiest to do using foobar2000 + vgmstream component since foobar has a built-in audio converter.
